#!/usr/bin/env python3
"""
Generate index.html from questions.md and status.md.

This script creates an interactive HTML status page with:
- Questions displayed in visually appealing cards
- Collapsible dropdowns showing status badges for each language
- Smooth animations and modern design
- Mobile-responsive layout
- Accessibility features (ARIA labels, keyboard navigation)

USAGE:
    python3 generate_html.py

HOW IT WORKS:
    1. Reads questions from questions.md
    2. Reads status badges from status.md (generated by update_status.py)
    3. Generates index.html with interactive features
    4. Idempotent - running multiple times produces the same result

The script is designed to be run automatically via GitHub Actions.
"""

import os
import re
from datetime import datetime

# --- CONFIGURATION ---
LANGUAGE_CONFIG = {
    "qbasic": "QBasic",
    "java": "Java",
    "python": "Python",
    "c": "C",
    "cpp": "C++",
    "csharp": "C#",
    "haskell": "Haskell",
    "perl": "Perl",
    "go": "Go",
    "elixir": "Elixir",
    "asm": "Assembly",
    "fortran": "Fortran",
    "lua": "Lua",
    "ruby": "Ruby",
    "vb": "Visual Basic",
    "pwsh": "PowerShell",
    "batch": "Batch",
}


def parse_questions(questions_file="questions.md"):
    """
    Parse questions from questions.md.

    Args:
        questions_file: Path to the questions markdown file

    Returns:
        List of dictionaries with 'number', 'text', 'filename', and 'example' keys
    """
    questions = []

    if not os.path.exists(questions_file):
        print(f"⚠️  Warning: {questions_file} not found.")
        return questions

    try:
        with open(questions_file, "r", encoding="utf-8") as f:
            lines = f.readlines()

        i = 0
        while i < len(lines):
            line = lines[i]
            # Pattern to match numbered questions
            # Example: "1. Print "Hello World". <br> [Filename - 0001_hello_world]"
            match = re.match(r"^(\d+)\.\s+(.+)$", line)

            if match:
                question_num = int(match.group(1))
                full_line = match.group(2).strip()
                
                # Extract filename if present
                filename = ""
                filename_match = re.search(r'\[Filename\s*-\s*([^\]]+)\]', full_line)
                if filename_match:
                    filename = filename_match.group(1).strip()
                
                # Extract question text (everything before <br>)
                question_text = full_line
                if '<br>' in full_line:
                    # Get text before <br>
                    parts = full_line.split('<br>')
                    question_text = parts[0].strip()
                else:
                    # Remove filename from question text if no <br>
                    question_text = re.sub(r'\s*\[Filename[^\]]+\]\s*$', '', question_text).strip()
                
                # Look for example code blocks in following lines (multi-line examples only)
                example = ""
                i += 1
                # Check if next lines contain code blocks (```)
                in_code_block = False
                example_lines = []
                
                while i < len(lines):
                    next_line = lines[i]
                    # Stop if we hit another numbered question
                    if re.match(r"^\d+\.\s+", next_line):
                        break
                    
                    # Check for code block markers
                    if next_line.strip().startswith('```'):
                        if in_code_block:
                            # End of code block - don't include the closing ```
                            in_code_block = False
                            i += 1
                            # Continue reading to catch any additional content
                            continue
                        else:
                            # Start of code block - don't include the opening ```
                            in_code_block = True
                            i += 1
                            continue
                    
                    # If we're in a code block, include the line
                    if in_code_block:
                        example_lines.append(next_line)
                        i += 1
                    # If line has content and looks like it's part of the question description
                    else:
                        stripped_line = next_line.strip()
                        if stripped_line and not stripped_line.startswith('#'):
                            # Check if this is a list item or continuation of question
                            if stripped_line.startswith('-') or next_line.startswith('    '):
                                example_lines.append(next_line)
                                i += 1
                            else:
                                break
                        elif stripped_line == '':
                            # Empty line - continue if we're building an example
                            if example_lines:
                                example_lines.append(next_line)
                            i += 1
                        else:
                            break
                
                if example_lines:
                    example = ''.join(example_lines).strip()
                
                questions.append({
                    "number": question_num,
                    "text": question_text,
                    "filename": filename,
                    "example": example
                })
                continue
            
            i += 1

        print(f"📊 Parsed {len(questions)} questions from {questions_file}")
        return questions

    except Exception as e:
        print(f"❌ Error parsing {questions_file}: {e}")
        return questions


def parse_status_badges(status_file="status.md"):
    """
    Parse status badges from status.md.

    Args:
        status_file: Path to the status markdown file

    Returns:
        Dictionary mapping question_number -> list of badge HTML/markdown
    """
    status_badges = {}

    if not os.path.exists(status_file):
        print(f"⚠️  Warning: {status_file} not found.")
        return status_badges

    try:
        with open(status_file, "r", encoding="utf-8") as f:
            lines = f.readlines()

        # Find the table section (starts after the header row)
        in_table = False
        languages = list(LANGUAGE_CONFIG.keys())

        for line in lines:
            # Skip header and divider rows
            if line.startswith("| #"):
                in_table = True
                continue
            if line.startswith("|:---"):
                continue
            if line.startswith("## Legend"):
                break

            if in_table and line.startswith("|"):
                # Parse table row
                cells = [cell.strip() for cell in line.split("|")]
                # Remove empty cells from start/end
                cells = [c for c in cells if c]

                if len(cells) >= 2:
                    # First cell is the question number
                    num_match = re.match(r"(\d+)", cells[0])
                    if num_match:
                        question_num = int(num_match.group(1))
                        # Remaining cells are the badges
                        badges = cells[1:]
                        status_badges[question_num] = badges

        print(f"📊 Parsed status badges for {
            len(status_badges)} questions from {status_file}")
        return status_badges

    except Exception as e:
        print(f"❌ Error parsing {status_file}: {e}")
        return status_badges


def convert_badge_to_html(badge_md):
    """
    Convert markdown badge to HTML.

    Args:
        badge_md: Markdown badge string (e.g., "[![done](...)](link)" or "![missing](...)")

    Returns:
        HTML string for the badge
    """
    # Pattern for clickable badge: [![alt](img_url)](link_url)
    clickable_pattern = r"\[\!\[([^\]]*)\]\(([^\)]+)\)\]\(([^\)]+)\)"
    match = re.match(clickable_pattern, badge_md)

    if match:
        alt_text = match.group(1)
        img_url = match.group(2)
        link_url = match.group(3)
        return f'<a href="{link_url}" target="_blank"><img src="{img_url}" alt="{alt_text}" class="badge"></a>'

    # Pattern for non-clickable badge: ![alt](img_url)
    non_clickable_pattern = r"\!\[([^\]]*)\]\(([^\)]+)\)"
    match = re.match(non_clickable_pattern, badge_md)

    if match:
        alt_text = match.group(1)
        img_url = match.group(2)
        return f'<img src="{img_url}" alt="{alt_text}" class="badge">'

    return badge_md


def generate_html(questions, status_badges):
    """
    Generate the complete HTML page.

    Args:
        questions: List of question dictionaries
        status_badges: Dictionary mapping question numbers to badge lists

    Returns:
        String containing the complete HTML
    """
    languages = list(LANGUAGE_CONFIG.values())
    current_year = datetime.now().year

    html_parts = []

    # HTML header and styles
    html_parts.append("""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Interactive programming questions and status page with solutions in 17+ languages">
    <meta name="theme-color" content="#2563eb" media="(prefers-color-scheme: light)">
    <meta name="theme-color" content="#1a1a1a" media="(prefers-color-scheme: dark)">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <title>Programming Questions & Status</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        html {
            overflow-x: hidden;
            width: 100%;
            scroll-behavior: smooth; /* Smooth scrolling */
        }

        /* Page load fade-in */
        html.page-loaded body {
            opacity: 1;
            transition: opacity 0.3s ease-in;
        }

        /* Theme transition animations */
        html.theme-transitioning,
        html.theme-transitioning *,
        html.theme-transitioning *::before,
        html.theme-transitioning *::after {
            transition: background-color 0.6s cubic-bezier(0.4, 0.0, 0.2, 1),
                        color 0.6s cubic-bezier(0.4, 0.0, 0.2, 1),
                        border-color 0.6s cubic-bezier(0.4, 0.0, 0.2, 1),
                        box-shadow 0.6s cubic-bezier(0.4, 0.0, 0.2, 1),
                        fill 0.6s cubic-bezier(0.4, 0.0, 0.2, 1),
                        stroke 0.6s cubic-bezier(0.4, 0.0, 0.2, 1) !important;
        }

        :root {
            --primary-color: #2563eb;
            --secondary-color: #1e40af;
            --accent-color: #3b82f6;
            --background: #f8fafc;
            --card-bg: #ffffff;
            --text-primary: #1e293b;
            --text-secondary: #64748b;
            --border-color: #e2e8f0;
            --shadow-sm: 0 1px 2px 0 rgba(0, 0, 0, 0.05);
            --shadow-md: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
            --shadow-lg: 0 10px 15px -3px rgba(0, 0, 0, 0.1);
            --shadow-xl: 0 20px 25px -5px rgba(0, 0, 0, 0.1);
        }

        /* Dark mode variables with enhanced colors */
        [data-theme="dark"] {
            --primary-color: #60a5fa;
            --secondary-color: #3b82f6;
            --accent-color: #93c5fd;
            --background: #0a0a0a;
            --card-bg: #1a1a1a;
            --text-primary: #f1f5f9;
            --text-secondary: #94a3b8;
            --border-color: #2a2a2a;
            --shadow-sm: 0 1px 2px 0 rgba(0, 0, 0, 0.5);
            --shadow-md: 0 4px 6px -1px rgba(0, 0, 0, 0.6);
            --shadow-lg: 0 10px 15px -3px rgba(0, 0, 0, 0.7);
            --shadow-xl: 0 20px 25px -5px rgba(0, 0, 0, 0.8);
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            background: linear-gradient(-45deg, #0a0e27, #1a1f3a, #0d1127, #181d35);
            background-size: 400% 400%;
            background-position: 0% 50%;
            animation: gradientShift 30s ease infinite, fadeIn 0.5s ease-in;
            color: var(--text-primary);
            line-height: 1.6;
            padding: 20px;
            position: relative;
            min-height: 100vh;
            overflow-x: hidden;
            width: 100%;
        }

        /* Subtle grid pattern overlay */
        body::after {
            content: '';
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-image: 
                linear-gradient(rgba(255, 255, 255, 0.02) 1px, transparent 1px),
                linear-gradient(90deg, rgba(255, 255, 255, 0.02) 1px, transparent 1px);
            background-size: 50px 50px;
            pointer-events: none;
            z-index: -1;
            opacity: 0.3;
        }

        [data-theme="light"] body::after {
            background-image: 
                linear-gradient(rgba(0, 0, 0, 0.03) 1px, transparent 1px),
                linear-gradient(90deg, rgba(0, 0, 0, 0.03) 1px, transparent 1px);
        }

        /* Enhanced dark mode body with smooth gradient transition */
        [data-theme="dark"] body {
            background: linear-gradient(-45deg, #000000, #0a0a0a, #050510, #0d0d1a);
            background-size: 400% 400%;
            background-position: 0% 50%;
            animation: gradientShift 30s ease infinite, fadeIn 0.5s ease-in;
        }
        
        /* Light mode override for space theme */
        [data-theme="light"] body {
            background: linear-gradient(-45deg, #e8f4f8, #f0f7fa, #eaf3f7, #f5f9fb);
            background-size: 400% 400%;
            background-position: 0% 50%;
        }

        @keyframes gradientShift {
            0% {
                background-position: 0% 50%;
            }
            50% {
                background-position: 100% 50%;
            }
            100% {
                background-position: 0% 50%;
            }
        }

        @keyframes fadeIn {
            from {
                opacity: 0;
            }
            to {
                opacity: 1;
            }
        }

        /* Cool Animated Background Elements */
        .bg-shapes {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            overflow: hidden;
            z-index: -2;
            pointer-events: none;
        }

        .bg-shape {
            position: absolute;
            border-radius: 50%;
            opacity: 0.08;
            animation: float 40s infinite ease-in-out;
        }

        .bg-shape:nth-child(1) {
            width: 250px;
            height: 250px;
            background: radial-gradient(circle, rgba(94, 201, 216, 0.25), transparent);
            top: 10%;
            left: 10%;
            animation-duration: 50s;
            animation-delay: 0s;
        }

        .bg-shape:nth-child(2) {
            width: 200px;
            height: 200px;
            background: radial-gradient(circle, rgba(126, 200, 227, 0.2), transparent);
            top: 60%;
            left: 70%;
            animation-duration: 60s;
            animation-delay: 5s;
        }

        .bg-shape:nth-child(3) {
            width: 220px;
            height: 220px;
            background: radial-gradient(circle, rgba(168, 230, 207, 0.22), transparent);
            top: 80%;
            left: 20%;
            animation-duration: 55s;
            animation-delay: 10s;
        }

        [data-theme="dark"] .bg-shape:nth-child(1) {
            background: radial-gradient(circle, rgba(30, 30, 30, 0.4), transparent);
        }

        [data-theme="dark"] .bg-shape:nth-child(2) {
            background: radial-gradient(circle, rgba(25, 25, 25, 0.35), transparent);
        }

        [data-theme="dark"] .bg-shape:nth-child(3) {
            background: radial-gradient(circle, rgba(35, 35, 35, 0.38), transparent);
        }

        @keyframes float {
            0%, 100% {
                transform: translate(0, 0) scale(1);
            }
            25% {
                transform: translate(15px, -20px) scale(1.05);
            }
            50% {
                transform: translate(-10px, -15px) scale(0.95);
            }
            75% {
                transform: translate(-20px, 10px) scale(1.02);
            }
        }

        /* Animated Particles */
        .bg-particles {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            overflow: hidden;
            z-index: -2;
            pointer-events: none;
        }

        .particle {
            position: absolute;
            width: 4px;
            height: 4px;
            background: rgba(255, 255, 255, 0.15);
            border-radius: 50%;
            animation: particleFloat 25s infinite ease-in-out;
        }

        .particle:nth-child(1) { left: 15%; animation-duration: 30s; animation-delay: 0s; }
        .particle:nth-child(2) { left: 40%; animation-duration: 35s; animation-delay: 5s; }
        .particle:nth-child(3) { left: 65%; animation-duration: 32s; animation-delay: 10s; }
        .particle:nth-child(4) { left: 85%; animation-duration: 38s; animation-delay: 3s; }

        @keyframes particleFloat {
            0% {
                transform: translateY(100vh) scale(0);
                opacity: 0;
            }
            10% {
                opacity: 0.2;
            }
            90% {
                opacity: 0.2;
            }
            100% {
                transform: translateY(-100px) scale(1);
                opacity: 0;
            }
        }

        [data-theme="dark"] .particle {
            background: rgba(255, 255, 255, 0.6);
        }

        /* Starfield Animation - Virgin Galactic inspired */
        .starfield {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            z-index: -3;
            pointer-events: none;
        }

        .star {
            position: absolute;
            background: white;
            border-radius: 50%;
            animation: twinkle 3s infinite;
        }

        @keyframes twinkle {
            0%, 100% { opacity: 0.3; transform: scale(1); }
            50% { opacity: 1; transform: scale(1.2); }
        }

        [data-theme="light"] .star {
            opacity: 0.1;
            background: #94a3b8;
        }

        /* Parallax scroll effects */
        .parallax-layer {
            transition: transform 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94);
        }

        /* Accessibility: Disable animations for users who prefer reduced motion */
        @media (prefers-reduced-motion: reduce) {
            html.theme-transitioning,
            html.theme-transitioning *,
            html.theme-transitioning *::before,
            html.theme-transitioning *::after {
                transition: none !important;
                animation: none !important;
            }
            
            body {
                animation: none !important;
            }
            .bg-shape,
            .particle {
                animation: none !important;
                opacity: 0.03 !important;
            }

            .theme-toggle:hover {
                transform: scale(1.05);
            }

            .theme-toggle #theme-icon {
                transition: none !important;
            }
        }

        body {
            padding-top: 80px; /* Space for sticky header */
        }

        /* Sticky Navigation Bar - Enhanced glassmorphism */
        .sticky-navbar {
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            background: rgba(248, 250, 252, 0.75);
            backdrop-filter: blur(20px) saturate(180%);
            -webkit-backdrop-filter: blur(20px) saturate(180%);
            border-bottom: 1px solid rgba(229, 231, 235, 0.5);
            box-shadow: 0 4px 24px rgba(0, 0, 0, 0.06);
            z-index: 1000;
            animation: slideDown 0.6s ease-out;
            transition: all 0.3s ease;
        }

        [data-theme="dark"] .sticky-navbar {
            background: rgba(10, 10, 10, 0.75);
            border-bottom: 1px solid rgba(255, 255, 255, 0.1);
            box-shadow: 0 4px 24px rgba(0, 0, 0, 0.3);
        }

        .navbar-content {
            max-width: 1400px;
            margin: 0 auto;
            padding: 12px 20px;
            display: flex;
            align-items: center;
            justify-content: space-between;
            gap: 20px;
        }

        .navbar-brand {
            display: flex;
            align-items: center;
            gap: 10px;
            font-size: 1.4rem;
            font-weight: 700;
            color: var(--primary-color);
            text-decoration: none;
            white-space: nowrap;
            flex-shrink: 0;
        }

        .navbar-brand:hover {
            opacity: 0.8;
        }

        .navbar-search {
            flex: 1;
            max-width: 500px;
            position: relative;
        }

        .navbar-actions {
            display: flex;
            align-items: center;
            gap: 12px;
            flex-shrink: 0;
        }

        @keyframes slideDown {
            from {
                transform: translateY(-30px);
                opacity: 0;
            }
            to {
                transform: translateY(0);
                opacity: 1;
            }
        }

        .container {
            max-width: 1400px;
            margin: 0 auto;
            padding: 0 8px;
            width: 100%;
            overflow-x: hidden;
        }

        header {
            text-align: center;
            padding: 60px 20px 40px;
            margin-bottom: 50px;
            position: relative;
            background: linear-gradient(135deg, rgba(37, 99, 235, 0.05), rgba(59, 130, 246, 0.05));
            border-radius: 24px;
            backdrop-filter: blur(10px);
            -webkit-backdrop-filter: blur(10px);
            border: 1px solid rgba(37, 99, 235, 0.1);
            overflow: hidden;
        }

        [data-theme="dark"] header {
            background: linear-gradient(135deg, rgba(96, 165, 250, 0.05), rgba(59, 130, 246, 0.08));
            border: 1px solid rgba(96, 165, 250, 0.15);
        }

        /* Fallback for browsers without backdrop-filter support */
        @supports not (backdrop-filter: blur(10px)) {
            header {
                background: linear-gradient(135deg, rgba(37, 99, 235, 0.15), rgba(59, 130, 246, 0.15));
            }
            [data-theme="dark"] header {
                background: linear-gradient(135deg, rgba(96, 165, 250, 0.15), rgba(59, 130, 246, 0.2));
            }
        }

        header::before {
            content: '';
            position: absolute;
            top: -50%;
            left: -50%;
            width: 200%;
            height: 200%;
            background: radial-gradient(
                circle,
                rgba(59, 130, 246, 0.1) 0%,
                transparent 70%
            );
            animation: heroGlow 8s ease-in-out infinite;
            pointer-events: none;
        }

        @keyframes heroGlow {
            0%, 100% {
                transform: translate(0, 0) scale(1);
                opacity: 0.5;
            }
            50% {
                transform: translate(10%, 10%) scale(1.1);
                opacity: 0.8;
            }
        }

        h1 {
            font-size: 3rem;
            font-weight: 800;
            background: linear-gradient(135deg, var(--primary-color), var(--accent-color));
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            background-clip: text;
            margin-bottom: 15px;
            display: flex;
            align-items: center;
            justify-content: center;
            gap: 15px;
            position: relative;
            z-index: 1;
            animation: slideInDown 0.8s ease-out;
        }

        @keyframes slideInDown {
            from {
                transform: translateY(-30px);
                opacity: 0;
            }
            to {
                transform: translateY(0);
                opacity: 1;
            }
        }

        .subtitle {
            font-size: 1.3rem;
            color: var(--text-secondary);
            margin-top: 10px;
            position: relative;
            z-index: 1;
            animation: fadeIn 1s ease-out 0.3s both;
        }

        @keyframes fadeIn {
            from {
                opacity: 0;
            }
            to {
                opacity: 1;
            }
        }

        .questions-grid {
            display: flex;
            flex-wrap: wrap;
            gap: 25px;
            margin-bottom: 40px;
        }

        @supports (display: grid) {
            .questions-grid {
                display: grid;
                grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
            }
        }

        /* Fallback for browsers without gap support */
        @supports not (gap: 25px) {
            .questions-grid {
                margin: -12.5px;
            }
            .question-card {
                margin: 12.5px;
            }
        }

        .question-card {
            background: var(--card-bg);
            border-radius: 16px;
            padding: 24px;
            box-shadow: var(--shadow-md);
            transition: all 0.4s cubic-bezier(0.25, 0.46, 0.45, 0.94);
            animation: fadeInUp 0.5s ease-out;
            animation-fill-mode: both;
            border: 1px solid var(--border-color);
            position: relative;
            overflow: hidden;
            transform-style: preserve-3d;
            backdrop-filter: blur(10px);
            -webkit-backdrop-filter: blur(10px);
        }

        /* Glassmorphism effect */
        [data-theme="dark"] .question-card {
            background: rgba(26, 26, 26, 0.7) !important;
            backdrop-filter: blur(20px);
            -webkit-backdrop-filter: blur(20px);
            border: 1px solid rgba(255, 255, 255, 0.1);
        }

        [data-theme="light"] .question-card {
            background: rgba(255, 255, 255, 0.8);
            backdrop-filter: blur(20px);
            -webkit-backdrop-filter: blur(20px);
        }

        /* Shine effect on hover */
        .question-card::before {
            content: '';
            position: absolute;
            top: -50%;
            left: -50%;
            width: 200%;
            height: 200%;
            background: linear-gradient(
                45deg,
                transparent 30%,
                rgba(255, 255, 255, 0.05) 50%,
                transparent 70%
            );
            transform: translateX(-100%) translateY(-100%) rotate(45deg);
            transition: transform 0.6s ease;
            pointer-events: none;
        }

        .question-card:hover::before {
            transform: translateX(100%) translateY(100%) rotate(45deg);
        }

        @keyframes fadeInUp {
            from {
                transform: translateY(20px);
                opacity: 0;
            }
            to {
                transform: translateY(0);
                opacity: 1;
            }
        }

        .question-card:hover {
            transform: translateY(-12px) scale(1.03) rotateX(2deg);
            box-shadow: 
                0 25px 50px -12px rgba(0, 0, 0, 0.25),
                0 0 40px rgba(59, 130, 246, 0.3);
            border-color: var(--accent-color);
        }

        .question-number {
            display: inline-block;
            background: linear-gradient(135deg, var(--primary-color), var(--secondary-color));
            color: white;
            padding: 6px 14px;
            border-radius: 20px;
            font-weight: 600;
            font-size: 0.875rem;
            margin-bottom: 12px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            transition: transform 0.3s ease, box-shadow 0.3s ease;
        }

        .question-card:hover .question-number {
            transform: scale(1.05);
            box-shadow: 0 4px 12px rgba(37, 99, 235, 0.4);
        }

        .question-text {
            font-size: 1.05rem;
            color: var(--text-primary);
            margin-bottom: 16px;
            line-height: 1.6;
        }

        .question-filename {
            font-family: 'Courier New', Courier, monospace;
            font-size: 0.9rem;
            color: var(--text-secondary);
            background: var(--background);
            padding: 8px 12px;
            border-radius: 6px;
            margin-bottom: 12px;
            border-left: 3px solid var(--primary-color);
            display: inline-block;
        }

        .question-example {
            font-family: 'Courier New', Courier, monospace;
            font-size: 0.875rem;
            color: var(--text-primary);
            background: var(--background);
            padding: 12px;
            border-radius: 6px;
            margin-bottom: 16px;
            white-space: pre-wrap;
            overflow-x: auto;
            border: 1px solid var(--border-color);
            line-height: 1.4;
        }

        .question-example code {
            font-family: inherit;
        }

        [data-theme="dark"] .question-card {
            background: #1a1a1a !important;
        }

        [data-theme="dark"] .question-card:hover {
            box-shadow: 
                0 0 50px rgba(96, 165, 250, 0.4),
                0 25px 50px -12px rgba(0, 0, 0, 0.5);
            border-color: rgba(96, 165, 250, 0.6);
        }

        [data-theme="dark"] .question-filename,
        [data-theme="dark"] .question-example {
            background: rgba(255, 255, 255, 0.03);
        }

        [data-theme="dark"] .status-toggle:hover {
            background: rgba(96, 165, 250, 0.1);
        }

        .status-toggle {
            background: none;
            border: none;
            width: 100%;
            text-align: left;
            padding: 12px 16px;
            background: var(--background);
            border-radius: 8px;
            cursor: pointer;
            font-size: 1rem;
            font-weight: 600;
            color: var(--primary-color);
            display: flex;
            align-items: center;
            justify-content: space-between;
            transition: all 0.3s ease;
        }

        .status-toggle:hover {
            background: #e0e7ff;
            transform: translateX(5px);
        }

        .status-toggle:focus {
            outline: 2px solid var(--accent-color);
            outline-offset: 2px;
        }

        .arrow {
            transition: transform 0.3s ease;
            font-size: 1.2rem;
        }

        .arrow.open {
            transform: rotate(180deg);
        }

        .status-content {
            max-height: 0;
            overflow: hidden;
            transition: max-height 0.4s ease;
        }

        .status-content.open {
            max-height: 1000px;
        }

        .status-table-wrapper {
            padding: 16px 0;
            animation: fadeIn 0.3s ease;
        }

        .status-table {
            width: 100%;
            overflow-x: auto;
            margin-top: 12px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 0.875rem;
        }

        th {
            background: var(--background);
            padding: 8px 4px;
            text-align: center;
            font-weight: 600;
            color: var(--text-secondary);
            border-bottom: 2px solid var(--border-color);
            font-size: 0.8rem;
        }

        td {
            padding: 8px 4px;
            text-align: center;
            border-bottom: 1px solid var(--border-color);
        }

        .badge {
            height: 20px;
            display: inline-block;
            vertical-align: middle;
        }

        /* Scroll reveal animation states */
        .parallax-layer {
            opacity: 0;
            transform: translateY(50px);
            transition: opacity 0.8s ease, transform 0.8s ease;
        }

        .parallax-layer.revealed {
            opacity: 1;
            transform: translateY(0);
        }

        footer {
            text-align: center;
            padding: 40px 20px;
            color: var(--text-secondary);
            font-size: 0.875rem;
            border-top: 1px solid var(--border-color);
            margin-top: 60px;
        }

        footer a {
            color: var(--primary-color);
            text-decoration: none;
        }

        footer a:hover {
            text-decoration: underline;
        }

        /* Theme Toggle Button - Enhanced with animations */
        .theme-toggle {
            background: var(--card-bg);
            border: 2px solid var(--border-color);
            border-radius: 50%;
            width: 44px;
            height: 44px;
            display: flex;
            align-items: center;
            justify-content: center;
            cursor: pointer;
            font-size: 1.3rem;
            box-shadow: var(--shadow-sm);
            transition: all 0.3s cubic-bezier(0.4, 0.0, 0.2, 1);
            position: relative;
            overflow: hidden;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        .theme-toggle::before {
            content: '';
            position: absolute;
            top: 50%;
            left: 50%;
            width: 0;
            height: 0;
            border-radius: 50%;
            background: radial-gradient(circle, rgba(255, 255, 255, 0.3), transparent);
            transform: translate(-50%, -50%);
            transition: width 0.6s, height 0.6s;
        }

        .theme-toggle.ripple::before {
            width: 200%;
            height: 200%;
        }

        .theme-toggle:hover {
            transform: scale(1.1) rotate(15deg);
            box-shadow: var(--shadow-md);
            background: var(--background);
        }

        .theme-toggle:active {
            transform: scale(0.95) rotate(-15deg);
        }

        .theme-toggle #theme-icon {
            transition: transform 0.6s cubic-bezier(0.68, -0.55, 0.265, 1.55);
            display: inline-block;
        }

        .theme-toggle.switching #theme-icon {
            transform: rotate(360deg) scale(0);
        }

        /* Search Box - Navbar version */
        .navbar-search .search-box {
            position: relative;
            width: 100%;
        }

        .navbar-search .search-input {
            width: 100%;
            padding: 10px 40px 10px 40px;
            font-size: 0.95rem;
            border: 2px solid var(--border-color);
            border-radius: 8px;
            background: var(--card-bg);
            color: var(--text-primary);
            outline: none;
            transition: all 0.3s ease;
        }

        .navbar-search .search-input:focus {
            border-color: var(--primary-color);
            box-shadow: 0 0 0 3px rgba(37, 99, 235, 0.1);
        }

        [data-theme="dark"] .navbar-search .search-input:focus {
            box-shadow: 0 0 0 3px rgba(96, 165, 250, 0.2);
        }

        .navbar-search .search-input::placeholder {
            color: var(--text-secondary);
        }

        .navbar-search .search-icon {
            position: absolute;
            left: 12px;
            top: 50%;
            transform: translateY(-50%);
            font-size: 1.1rem;
            color: var(--text-secondary);
            pointer-events: none;
        }

        .navbar-search .clear-search {
            position: absolute;
            right: 12px;
            top: 50%;
            transform: translateY(-50%);
            background: none;
            border: none;
            font-size: 1.1rem;
            color: var(--text-secondary);
            cursor: pointer;
            padding: 4px;
            opacity: 0;
            transition: opacity 0.2s ease;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .navbar-search .clear-search.visible {
            opacity: 1;
        }

        .navbar-search .clear-search:hover {
            color: var(--text-primary);
        }

        /* Legacy search container (kept for compatibility) */
        .search-container {
            max-width: 600px;
            margin: 0 auto 40px auto;
            display: none; /* Hidden as search is now in navbar */
        }

        .search-box {
            position: relative;
            width: 100%;
        }

        .search-input {
            width: 100%;
            padding: 16px 50px 16px 50px;
            font-size: 1.05rem;
            border: 2px solid var(--border-color);
            border-radius: 12px;
            background: var(--card-bg);
            color: var(--text-primary);
            outline: none;
            transition: all 0.3s ease;
            box-shadow: var(--shadow-sm);
        }

        .search-input:focus {
            border-color: var(--primary-color);
            box-shadow: 0 0 0 3px rgba(37, 99, 235, 0.1);
        }

        [data-theme="dark"] .search-input:focus {
            box-shadow: 0 0 0 3px rgba(96, 165, 250, 0.2);
        }

        .search-input::placeholder {
            color: var(--text-secondary);
        }

        .search-input::-webkit-input-placeholder {
            color: var(--text-secondary);
        }

        .search-input::-moz-placeholder {
            color: var(--text-secondary);
        }

        .search-input:-ms-input-placeholder {
            color: var(--text-secondary);
        }

        .search-icon {
            position: absolute;
            left: 18px;
            top: 50%;
            transform: translateY(-50%);
            font-size: 1.3rem;
            color: var(--text-secondary);
            pointer-events: none;
        }

        .clear-search {
            position: absolute;
            right: 18px;
            top: 50%;
            transform: translateY(-50%);
            background: none;
            border: none;
            font-size: 1.3rem;
            color: var(--text-secondary);
            cursor: pointer;
            padding: 4px;
            opacity: 0;
            transition: opacity 0.2s ease;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .clear-search.visible {
            opacity: 1;
        }

        .clear-search:hover {
            color: var(--text-primary);
        }

        .search-results-info {
            text-align: center;
            margin-top: 12px;
            font-size: 0.95rem;
            color: var(--text-secondary);
        }

        .no-results {
            text-align: center;
            padding: 60px 20px;
            color: var(--text-secondary);
            font-size: 1.1rem;
        }

        .no-results-icon {
            font-size: 3rem;
            margin-bottom: 16px;
        }

        .question-card.hidden {
            display: none;
        }

        /* Badge Tip Section */
        .badge-tip {
            background: linear-gradient(135deg, #fef3c7 0%, #fde68a 100%);
            border-left: 4px solid #f59e0b;
            padding: 16px 20px;
            border-radius: 8px;
            margin-bottom: 40px;
            display: flex;
            align-items: center;
            gap: 12px;
            box-shadow: var(--shadow-sm);
            animation: slideDown 0.6s ease-out;
        }

        [data-theme="dark"] .badge-tip {
            background: linear-gradient(135deg, #422006 0%, #713f12 100%);
            border-left-color: #f59e0b;
        }

        .badge-tip-icon {
            font-size: 1.5rem;
            flex-shrink: 0;
        }

        .badge-tip-text {
            color: #78350f;
            font-weight: 500;
            font-size: 1rem;
        }

        [data-theme="dark"] .badge-tip-text {
            color: #fde68a;
        }

        /* Scroll Progress Indicator - Enhanced */
        .scroll-progress {
            position: fixed;
            top: 0;
            left: 0;
            height: 4px;
            background: linear-gradient(90deg, 
                var(--primary-color) 0%, 
                var(--accent-color) 50%,
                #a78bfa 100%
            );
            box-shadow: 0 2px 10px rgba(59, 130, 246, 0.5);
            z-index: 1001;
            transition: width 0.15s ease-out;
            width: 0%;
        }

        [data-theme="dark"] .scroll-progress {
            box-shadow: 0 2px 15px rgba(96, 165, 250, 0.6);
        }

        /* Back to Top Button - Enhanced */
        .back-to-top {
            position: fixed;
            bottom: 30px;
            right: 30px;
            width: 56px;
            height: 56px;
            background: linear-gradient(135deg, var(--primary-color), var(--accent-color));
            color: white;
            border: none;
            border-radius: 50%;
            font-size: 1.5rem;
            cursor: pointer;
            box-shadow: 0 8px 20px rgba(37, 99, 235, 0.3);
            opacity: 0;
            visibility: hidden;
            transition: all 0.4s cubic-bezier(0.25, 0.46, 0.45, 0.94);
            z-index: 999;
            display: flex;
            align-items: center;
            justify-content: center;
            backdrop-filter: blur(10px);
            -webkit-backdrop-filter: blur(10px);
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        .back-to-top.visible {
            opacity: 1;
            visibility: visible;
        }

        .back-to-top:hover {
            transform: translateY(-8px) scale(1.1);
            box-shadow: 0 12px 30px rgba(37, 99, 235, 0.5);
        }

        .back-to-top:active {
            transform: translateY(-5px) scale(1.05);
        }

        /* Enhanced card animations and hover effects */
        .question-card {
            position: relative;
            overflow: hidden;
        }

        .question-card::before {
            content: '';
            position: absolute;
            top: 0;
            left: -100%;
            width: 100%;
            height: 100%;
            background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.1), transparent);
            transition: left 0.5s ease;
        }

        .question-card:hover::before {
            left: 100%;
        }

        /* Search results info */
        .search-results-info {
            text-align: center;
            margin-top: 12px;
            font-size: 0.95rem;
            color: var(--text-secondary);
        }

        @media (max-width: 768px) {
            body {
                padding: 12px;
                padding-top: 70px; /* Adjust for smaller navbar on mobile */
                line-height: 1.5;
            }

            .navbar-content {
                padding: 10px 12px;
                flex-wrap: wrap;
            }

            .navbar-brand {
                font-size: 1.1rem;
            }

            .navbar-search {
                order: 3;
                flex: 1 1 100%;
                margin-top: 10px;
                max-width: 100%;
            }

            .navbar-actions {
                order: 2;
            }

            .theme-toggle {
                width: 40px;
                height: 40px;
                font-size: 1.1rem;
            }

            .back-to-top {
                bottom: 20px;
                right: 20px;
                width: 44px;
                height: 44px;
                font-size: 1.3rem;
            }

            h1 {
                font-size: 1.75rem;
                flex-direction: column;
                gap: 8px;
            }

            .subtitle {
                font-size: 1rem;
                margin-top: 8px;
            }

            header {
                padding: 24px 12px;
                margin-bottom: 24px;
            }

            .questions-grid {
                grid-template-columns: 1fr;
                gap: 16px;
            }

            .question-card {
                padding: 16px;
                border-radius: 8px;
            }

            .question-number {
                padding: 5px 12px;
                font-size: 0.8rem;
                margin-bottom: 10px;
            }

            .question-text {
                font-size: 0.95rem;
                line-height: 1.5;
            }

            .status-header {
                padding: 12px 16px;
                font-size: 0.9rem;
                min-height: 48px;
            }

            .status-icon {
                font-size: 1rem;
            }

            .status-count {
                font-size: 0.8rem;
            }

            .status-table-wrapper {
                padding: 12px 0;
            }

            th, td {
                padding: 8px 4px;
                font-size: 0.7rem;
            }

            th {
                font-size: 0.65rem;
            }

            .search-container {
                margin-bottom: 24px;
            }

            .search-input {
                padding: 14px 44px 14px 44px;
                font-size: 1rem;
                border-radius: 10px;
            }

            .search-icon {
                font-size: 1.2rem;
                left: 14px;
            }

            .clear-search {
                font-size: 1.2rem;
                right: 14px;
            }

            .splash-title {
                font-size: 1.5rem;
            }

            .splash-subtitle {
                font-size: 0.85rem;
            }

            .theme-toggle {
                width: 52px;
                height: 52px;
                font-size: 1.4rem;
                top: 12px;
                right: 12px;
            }

            footer {
                padding: 24px 12px;
                margin-top: 40px;
                font-size: 0.8rem;
            }

            .badge-tip {
                padding: 12px;
                margin: 12px 16px;
                font-size: 0.85rem;
            }

            .badge-tip-icon {
                font-size: 1.2rem;
            }

            .badge-tip-text {
                font-size: 0.85rem;
            }
        }

        /* Additional mobile improvements for very small screens */
        @media (max-width: 480px) {
            body {
                padding: 8px;
            }

            h1 {
                font-size: 1.5rem;
            }

            .subtitle {
                font-size: 0.9rem;
            }

            header {
                padding: 20px 8px;
                margin-bottom: 20px;
            }

            .questions-grid {
                gap: 12px;
            }

            .question-card {
                padding: 14px;
            }

            .question-text {
                font-size: 0.9rem;
            }

            .search-input {
                padding: 12px 40px 12px 40px;
                font-size: 0.95rem;
            }

            .theme-toggle {
                width: 48px;
                height: 48px;
                font-size: 1.3rem;
                top: 8px;
                right: 8px;
            }

            .status-header {
                padding: 10px 14px;
                font-size: 0.85rem;
                min-height: 44px;
            }

            th, td {
                padding: 6px 2px;
                font-size: 0.65rem;
            }

            th {
                font-size: 0.6rem;
            }
        }

        /* Stagger animation for cards */
        """)

    # Add staggered animation delays for cards
    for i in range(min(len(questions), 100)):
        delay = i * 0.03
        html_parts.append(
            f"        .question-card:nth-child({i + 1}) {{ animation-delay: {delay}s; }}\n"
        )

    html_parts.append("""
        /* Splash Screen Styles - Linux Boot Style */
        #splash-screen {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%);
            display: flex;
            flex-direction: column;
            align-items: flex-start;
            justify-content: flex-start;
            padding: 40px;
            z-index: 9999;
            overflow-y: auto;
            overflow-x: hidden;
            font-family: 'Courier New', Consolas, Monaco, monospace;
        }

        #splash-screen.hidden {
            animation: splashFadeOut 0.6s ease-out forwards;
        }

        @keyframes splashFadeOut {
            from {
                opacity: 1;
            }
            to {
                opacity: 0;
                visibility: hidden;
            }
        }

        .boot-line {
            color: #00ff00;
            font-size: 0.9rem;
            line-height: 1.6;
            margin: 2px 0;
            opacity: 0;
            animation: bootLineAppear 0.1s ease-out forwards;
            word-wrap: break-word;
        }

        @keyframes bootLineAppear {
            from {
                opacity: 0;
                transform: translateX(-5px);
            }
            to {
                opacity: 1;
                transform: translateX(0);
            }
        }

        .boot-line.info {
            color: #00d4ff;
        }

        .boot-line.warning {
            color: #ffaa00;
        }

        .boot-line.error {
            color: #ff4444;
        }

        .boot-line.highlight {
            color: #ffffff;
            font-weight: bold;
        }

        .boot-status {
            display: inline-block;
            min-width: 60px;
            text-align: center;
            font-weight: bold;
        }

        .boot-status.ok {
            color: #00ff00;
        }

        .boot-status.failed {
            color: #ff4444;
        }

        .boot-cursor {
            display: inline-block;
            width: 10px;
            height: 16px;
            background: #00ff00;
            margin-left: 5px;
            animation: cursorBlink 1s infinite;
        }

        @keyframes cursorBlink {
            0%, 49% {
                opacity: 1;
            }
            50%, 100% {
                opacity: 0;
            }
        }

        #skip-splash-btn {
            position: fixed;
            bottom: 30px;
            right: 30px;
            background: rgba(0, 255, 0, 0.2);
            color: #00ff00;
            border: 2px solid #00ff00;
            padding: 12px 24px;
            font-family: 'Courier New', Consolas, Monaco, monospace;
            font-size: 0.9rem;
            cursor: pointer;
            border-radius: 4px;
            z-index: 10000;
            transition: all 0.3s ease;
        }

        #skip-splash-btn:hover {
            background: rgba(0, 255, 0, 0.3);
            transform: scale(1.05);
        }

        #skip-splash-btn:active {
            transform: scale(0.95);
        }

        /* Mobile responsiveness for splash screen */
        @media (max-width: 768px) {
            #splash-screen {
                padding: 20px;
            }

            .boot-line {
                font-size: 0.75rem;
                line-height: 1.4;
            }

            #skip-splash-btn {
                bottom: 15px;
                right: 15px;
                padding: 10px 18px;
                font-size: 0.8rem;
            }
        }

        @media (max-width: 480px) {
            #splash-screen {
                padding: 15px;
            }

            .boot-line {
                font-size: 0.7rem;
                line-height: 1.3;
            }

            #skip-splash-btn {
                bottom: 10px;
                right: 10px;
                padding: 8px 14px;
                font-size: 0.75rem;
            }
        }
    </style>
    <script>
        // Set theme immediately before page renders to prevent flash
        (function() {
            const savedTheme = localStorage.getItem('theme') || 'light';
            document.documentElement.setAttribute('data-theme', savedTheme);
        })();
    </script>
</head>
<body>
    <!-- Noscript fallback for browsers with JavaScript disabled -->
    <noscript>
        <div style="position: fixed; top: 0; left: 0; right: 0; background: #fef3c7; color: #92400e; padding: 20px; text-align: center; z-index: 10000; border-bottom: 3px solid #f59e0b; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;">
            <strong>⚠️ JavaScript Required:</strong> This interactive page requires JavaScript to be enabled for full functionality. Please enable JavaScript in your browser settings.
        </div>
    </noscript>

    <!-- Cool Animated Background Elements -->
    <div class="bg-shapes">
        <div class="bg-shape"></div>
        <div class="bg-shape"></div>
        <div class="bg-shape"></div>
    </div>
    <div class="bg-particles">
        <div class="particle"></div>
        <div class="particle"></div>
        <div class="particle"></div>
        <div class="particle"></div>
    </div>

    <!-- Splash Screen - Linux Boot Style -->
    <div id="splash-screen">
        <div id="boot-messages"></div>
        <button id="skip-splash-btn" onclick="skipSplash()">Skip [ESC]</button>
    </div>

    <!-- Scroll Progress Indicator -->
    <div class="scroll-progress" id="scrollProgress"></div>

    <!-- Sticky Navigation Bar -->
    <nav class="sticky-navbar">
        <div class="navbar-content">
            <a href="#" class="navbar-brand" onclick="scrollToTop(); return false;">
                <span>📘</span>
                <span>Programming Questions</span>
            </a>
            <div class="navbar-search">
                <div class="search-box">
                    <span class="search-icon">🔍</span>
                    <input 
                        type="text" 
                        id="searchInput" 
                        class="search-input" 
                        placeholder="Search questions..."
                        aria-label="Search questions"
                        autocomplete="off"
                    >
                    <button 
                        id="clearSearch" 
                        class="clear-search" 
                        aria-label="Clear search"
                        onclick="clearSearch()"
                    >✕</button>
                </div>
            </div>
            <div class="navbar-actions">
                <button class="theme-toggle" onclick="toggleTheme()" aria-label="Toggle dark mode">
                    <span id="theme-icon">🌙</span>
                </button>
            </div>
        </div>
    </nav>

    <!-- Back to Top Button -->
    <button class="back-to-top" id="backToTop" onclick="scrollToTop()" aria-label="Back to top">
        ↑
    </button>

    <div class="container">
        <header>
            <h1>
                <span>📘</span>
                <span>Programming Questions & Status</span>
            </h1>
        </header>

        <!-- Search Box -->
        <div class="search-container">
            <div class="search-box">
                <span class="search-icon">🔍</span>
                <input 
                    type="text" 
                    id="searchInput" 
                    class="search-input" 
                    placeholder="Search questions by number or description..."
                    aria-label="Search questions"
                    autocomplete="off"
                >
                <button 
                    id="clearSearch" 
                    class="clear-search" 
                    aria-label="Clear search"
                    onclick="clearSearch()"
                >✕</button>
            </div>
            <div id="searchResultsInfo" class="search-results-info"></div>
        </div>

        <!-- Badge Tip -->
        <div class="badge-tip">
            <div class="badge-tip-icon">💡</div>
            <div class="badge-tip-text">Tip: Click on the badges to view the code</div>
        </div>

        <div id="noResults" class="no-results" style="display: none;">
            <div class="no-results-icon">🔍</div>
            <div>No questions found matching your search.</div>
        </div>

        <div class="questions-grid" id="questionsGrid">
""")

    # Generate question cards
    for question in questions:
        qnum = question["number"]
        qtext = question["text"]
        qfilename = question.get("filename", "")
        qexample = question.get("example", "")
        badges = status_badges.get(qnum, [])

        html_parts.append(f"""            <div class="question-card">
                <div class="question-number">#{qnum:04d}</div>
                <div class="question-text">{qtext}</div>""")
        
        # Add filename if present
        if qfilename:
            html_parts.append(f"""
                <div class="question-filename">📁 {qfilename}</div>""")
        
        # Add example if present
        if qexample:
            # Escape HTML in example to prevent injection
            qexample_escaped = qexample.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
            html_parts.append(f"""
                <div class="question-example">{qexample_escaped}</div>""")
        
        html_parts.append(f"""
                <button class="status-toggle"
                        aria-expanded="false"
                        aria-controls="status-{qnum}"
                        onclick="toggleStatus({qnum})">
                    <span>Status</span>
                    <span class="arrow" id="arrow-{qnum}">▼</span>
                </button>
                <div class="status-content" id="status-{qnum}" role="region" aria-hidden="true">
                    <div class="status-table-wrapper">
                        <div class="status-table">
                            <table>
                                <thead>
                                    <tr>
""")

        # Add language headers
        for lang in languages:
            html_parts.append(
                f"                                        <th>{lang}</th>\n"
            )

        html_parts.append("""                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
""")

        # Add badges for each language
        for badge_md in badges[
            : len(languages)
        ]:  # Ensure we don't exceed language count
            badge_html = convert_badge_to_html(badge_md)
            html_parts.append(
                f"                                        <td>{badge_html}</td>\n")

        # Fill remaining cells if needed
        for _ in range(len(languages) - len(badges)):
            html_parts.append(
                "                                        <td>-</td>\n")

        html_parts.append("""                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
""")

    # Add footer and JavaScript
    html_parts.append(f"""        </div>

        <footer>
            <p>Generated on {datetime.now().strftime("%B %d, %Y at %H:%M UTC")}</p>
            <p>
                <a href="https://github.com/DibyajyotiBiswal57/programs" target="_blank">View on GitHub</a>
            </p>
            <p>&copy; {current_year} Programming Questions Project</p>
        </footer>
    </div>

    <script>
        // Enhanced Theme Toggle with Smooth Animations
        function toggleTheme() {{
            const html = document.documentElement;
            const currentTheme = html.getAttribute('data-theme');
            const newTheme = currentTheme === 'dark' ? 'light' : 'dark';
            const themeButton = document.querySelector('.theme-toggle');
            const themeIcon = document.getElementById('theme-icon');

            // Add ripple effect
            themeButton.classList.add('ripple');
            setTimeout(() => themeButton.classList.remove('ripple'), 600);

            // Add switching animation to icon
            themeButton.classList.add('switching');

            // Add transitioning class for smooth color changes
            html.classList.add('theme-transitioning');

            // Change theme after brief delay for smoother transition
            setTimeout(() => {{
                html.setAttribute('data-theme', newTheme);
                localStorage.setItem('theme', newTheme);

                // Update icon with rotation animation
                setTimeout(() => {{
                    themeIcon.textContent = newTheme === 'dark' ? '☀️' : '🌙';
                    themeButton.classList.remove('switching');
                }}, 300);

                // Create particles effect during transition
                createThemeParticles(newTheme);

                // Remove transitioning class after animation completes
                setTimeout(() => {{
                    html.classList.remove('theme-transitioning');
                }}, 600);
            }}, 50);
        }}

        // Create particle effect during theme transition
        function createThemeParticles(theme) {{
            // Use theme-appropriate colors from CSS variables
            const sharedColor = '#3b82f6';
            const colors = theme === 'dark' 
                ? ['#60a5fa', sharedColor, '#93c5fd']
                : ['#2563eb', sharedColor, '#1e40af'];
            
            const button = document.querySelector('.theme-toggle');
            const rect = button.getBoundingClientRect();
            const centerX = rect.left + rect.width / 2;
            const centerY = rect.top + rect.height / 2;

            for (let i = 0; i < 12; i++) {{
                const particle = document.createElement('div');
                particle.style.cssText = `
                    position: fixed;
                    width: 6px;
                    height: 6px;
                    background: ${{colors[i % colors.length]}};
                    border-radius: 50%;
                    pointer-events: none;
                    z-index: 9999;
                    left: ${{centerX}}px;
                    top: ${{centerY}}px;
                `;
                document.body.appendChild(particle);

                const angle = (i / 12) * Math.PI * 2;
                const velocity = 100 + Math.random() * 50;
                const tx = Math.cos(angle) * velocity;
                const ty = Math.sin(angle) * velocity;

                particle.animate([
                    {{ transform: 'translate(0, 0) scale(1)', opacity: 1 }},
                    {{ transform: `translate(${{tx}}px, ${{ty}}px) scale(0)`, opacity: 0 }}
                ], {{
                    duration: 800,
                    easing: 'cubic-bezier(0.4, 0.0, 0.2, 1)'
                }}).onfinish = () => particle.remove();
            }}
        }}

        // Initialize theme-dependent UI elements after DOM is ready
        (function() {{
            const savedTheme = localStorage.getItem('theme') || 'light';
            const themeIcon = document.getElementById('theme-icon');

            // Set initial icon based on current theme
            if (themeIcon) {{
                themeIcon.textContent = savedTheme === 'dark' ? '☀️' : '🌙';
            }}

            // Add loaded class for fade-in animation
            setTimeout(() => {{
                document.documentElement.classList.add('page-loaded');
            }}, 50);
        }})();

        // Scroll to top function
        function scrollToTop() {{
            window.scrollTo({{
                top: 0,
                behavior: 'smooth'
            }});
        }}

        // Combined scroll handler for performance
        const backToTopBtn = document.getElementById('backToTop');
        const scrollProgress = document.getElementById('scrollProgress');
        
        window.addEventListener('scroll', function() {{
            // Back to top button visibility
            if (window.pageYOffset > 300) {{
                backToTopBtn.classList.add('visible');
            }} else {{
                backToTopBtn.classList.remove('visible');
            }}
            
            // Scroll progress indicator
            const winScroll = document.body.scrollTop || document.documentElement.scrollTop;
            const height = document.documentElement.scrollHeight - document.documentElement.clientHeight;
            const scrolled = (winScroll / height) * 100;
            scrollProgress.style.width = scrolled + '%';
        }});

        // Keyboard shortcuts
        document.addEventListener('keydown', function(event) {{
            // Ctrl/Cmd + K to focus search
            if ((event.ctrlKey || event.metaKey) && event.key === 'k') {{
                event.preventDefault();
                searchInput.focus();
            }}
            // ESC to clear search
            if (event.key === 'Escape' && document.activeElement === searchInput) {{
                clearSearch();
                searchInput.blur();
            }}
            
            if (event.target.classList.contains('status-toggle')) {{
                if (event.key === 'Enter' || event.key === ' ') {{
                    event.preventDefault();
                    event.target.click();
                }}
            }}
        }});

        function toggleStatus(questionNumber) {{
            const content = document.getElementById('status-' + questionNumber);
            const arrow = document.getElementById('arrow-' + questionNumber);
            const button = content.previousElementSibling;

            const isOpen = content.classList.contains('open');

            if (isOpen) {{
                content.classList.remove('open');
                arrow.classList.remove('open');
                button.setAttribute('aria-expanded', 'false');
                content.setAttribute('aria-hidden', 'true');
            }} else {{
                content.classList.add('open');
                arrow.classList.add('open');
                button.setAttribute('aria-expanded', 'true');
                content.setAttribute('aria-hidden', 'false');
            }}
        }}

        // Search functionality
        let searchTimeout;
        const searchInput = document.getElementById('searchInput');
        const clearButton = document.getElementById('clearSearch');
        const searchResultsInfo = document.getElementById('searchResultsInfo');
        const questionsGrid = document.getElementById('questionsGrid');
        const noResultsDiv = document.getElementById('noResults');

        function performSearch() {{
            const searchTerm = searchInput.value.toLowerCase().trim();
            const questionCards = questionsGrid.querySelectorAll('.question-card');
            let visibleCount = 0;
            let totalCount = questionCards.length;

            questionCards.forEach(card => {{
                const questionNumber = card.querySelector('.question-number').textContent.toLowerCase();
                const questionText = card.querySelector('.question-text').textContent.toLowerCase();
                
                const matches = questionNumber.includes(searchTerm) || questionText.includes(searchTerm);
                
                if (matches) {{
                    card.classList.remove('hidden');
                    visibleCount++;
                }} else {{
                    card.classList.add('hidden');
                }}
            }});

            // Update UI based on results
            if (searchTerm === '') {{
                searchResultsInfo.textContent = '';
                clearButton.classList.remove('visible');
                noResultsDiv.style.display = 'none';
                questionsGrid.style.display = 'grid';
            }} else {{
                clearButton.classList.add('visible');
                if (visibleCount === 0) {{
                    searchResultsInfo.textContent = '';
                    noResultsDiv.style.display = 'block';
                    questionsGrid.style.display = 'none';
                }} else {{
                    searchResultsInfo.textContent = `Showing ${{visibleCount}} of ${{totalCount}} questions`;
                    noResultsDiv.style.display = 'none';
                    questionsGrid.style.display = 'grid';
                }}
            }}
        }}

        function clearSearch() {{
            searchInput.value = '';
            performSearch();
            searchInput.focus();
        }}

        // Debounced search as user types
        searchInput.addEventListener('input', function() {{
            clearTimeout(searchTimeout);
            searchTimeout = setTimeout(performSearch, 300);
        }});

        // Also search on Enter key
        searchInput.addEventListener('keypress', function(event) {{
            if (event.key === 'Enter') {{
                clearTimeout(searchTimeout);
                performSearch();
            }}
        }});

        // Splash screen initialization with real file loading tracking
        (function() {{
            const bootMessages = document.getElementById('boot-messages');

            // Function to add a boot message
            function addBootMessage(text, status = null, className = '') {{
                const line = document.createElement('div');
                line.className = 'boot-line ' + className;
                
                if (status) {{
                    const statusSpan = document.createElement('span');
                    statusSpan.className = 'boot-status ' + (status === 'OK' ? 'ok' : 'failed');
                    statusSpan.textContent = status === 'OK' ? '[  OK  ]' : '[FAILED]';
                    line.appendChild(statusSpan);
                    line.appendChild(document.createTextNode(' ' + text));
                }} else {{
                    line.textContent = text;
                }}
                
                bootMessages.appendChild(line);
                return line;
            }}

            // Initialize boot sequence
            addBootMessage('Starting Programming Questions Bootloader...', 'OK');
            addBootMessage('Initializing system modules...', null, 'info');

            // Monitor resource loading
            function trackResourceLoading() {{
                let loadedResources = {{
                    stylesheet: 0,
                    script: 0,
                    image: 0
                }};

                let failedResources = {{
                    stylesheet: 0,
                    script: 0,
                    image: 0
                }};

                // Track stylesheets (already loaded)
                const stylesheets = document.querySelectorAll('link[rel="stylesheet"]');
                const totalStylesheets = stylesheets.length;
                
                if (totalStylesheets > 0) {{
                    // Stylesheets are inline, consider them loaded
                    loadedResources.stylesheet = totalStylesheets;
                    addBootMessage('Loaded ' + totalStylesheets + ' stylesheet(s)', 'OK', 'info');
                }}

                // Track inline and external scripts by checking if they execute
                // Since we can't easily track inline scripts, we'll just indicate JavaScript is ready
                const allScripts = document.querySelectorAll('script');
                const externalScripts = Array.from(allScripts).filter(s => s.src);
                
                if (externalScripts.length > 0) {{
                    externalScripts.forEach(function(script) {{
                        const scriptName = script.src.split('/').pop();
                        addBootMessage('Loaded script: ' + scriptName, 'OK', 'info');
                        loadedResources.script++;
                    }});
                }} else {{
                    addBootMessage('All JavaScript modules loaded', 'OK', 'info');
                }}

                // Helper function to report image loading results
                function reportImageResults(loaded, failed) {{
                    if (loaded > 0) {{
                        addBootMessage('Loaded ' + loaded + ' image(s)', 'OK', 'info');
                    }}
                    if (failed > 0) {{
                        addBootMessage('Failed to load ' + failed + ' image(s)', 'FAILED', 'error');
                    }}
                }}

                // Track images
                const images = document.querySelectorAll('img');
                if (images.length > 0) {{
                    let imagesLoaded = 0;
                    let imagesFailed = 0;
                    
                    function checkAllImagesProcessed() {{
                        if (imagesLoaded + imagesFailed === images.length) {{
                            reportImageResults(imagesLoaded, imagesFailed);
                        }}
                    }}
                    
                    images.forEach(function(img) {{
                        if (img.complete) {{
                            if (img.naturalHeight > 0) {{
                                imagesLoaded++;
                                loadedResources.image++;
                            }} else {{
                                imagesFailed++;
                                failedResources.image++;
                            }}
                        }} else {{
                            img.addEventListener('load', function() {{
                                imagesLoaded++;
                                loadedResources.image++;
                                checkAllImagesProcessed();
                            }});
                            img.addEventListener('error', function() {{
                                imagesFailed++;
                                failedResources.image++;
                                checkAllImagesProcessed();
                            }});
                        }}
                    }});
                    
                    checkAllImagesProcessed();
                }} else {{
                    addBootMessage('No images to load', 'OK', 'info');
                }}
            }}

            // Start tracking
            setTimeout(function() {{
                addBootMessage('Mounted /dev/sda1 on /questions', 'OK');
                addBootMessage('Started Language Runtime Services', 'OK');
            }}, 100);

            setTimeout(function() {{
                trackResourceLoading();
            }}, 200);

            setTimeout(function() {{
                addBootMessage('Started Progress Tracking Service', 'OK');
                addBootMessage('Reached target Multi-Language Support', 'OK');
            }}, 400);

            setTimeout(function() {{
                const questionCards = document.querySelectorAll('.question-card');
                addBootMessage('Checking status badges... ' + questionCards.length + ' questions found.', null, 'warning');
            }}, 600);

            setTimeout(function() {{
                addBootMessage('Started Dark Mode Theme Service', 'OK');
                addBootMessage('Started Web Interface', 'OK');
            }}, 800);

            setTimeout(function() {{
                const line = document.createElement('div');
                line.className = 'boot-line highlight';
                line.innerHTML = '<br>Programming Questions v1.0 - Ready';
                bootMessages.appendChild(line);
                
                const finalLine = document.createElement('div');
                finalLine.className = 'boot-line info';
                finalLine.innerHTML = 'System boot complete. Starting interface...<span class="boot-cursor"></span>';
                bootMessages.appendChild(finalLine);
            }}, 1000);
        }})();

        // Skip splash screen function
        function skipSplash() {{
            const splashScreen = document.getElementById('splash-screen');
            if (splashScreen) {{
                splashScreen.classList.add('hidden');
                setTimeout(function() {{
                    splashScreen.remove();
                }}, 600);
            }}
        }}

        // ESC key to skip splash
        document.addEventListener('keydown', function(e) {{
            if (e.key === 'Escape') {{
                skipSplash();
            }}
        }});

        // Auto-hide splash screen after delay
        window.addEventListener('load', function() {{
            setTimeout(function() {{
                skipSplash();
            }}, 4000); // 4 seconds to see all the loading messages
        }});

        // Virgin Galactic-inspired scroll reveal animations
        const observerOptions = {{
            threshold: 0.1,
            rootMargin: '0px 0px -100px 0px'
        }};

        const revealObserver = new IntersectionObserver(function(entries) {{
            entries.forEach(function(entry) {{
                if (entry.isIntersecting) {{
                    entry.target.classList.add('revealed');
                    // Add stagger effect
                    const cards = document.querySelectorAll('.question-card');
                    cards.forEach(function(card, index) {{
                        if (card === entry.target) {{
                            card.style.transitionDelay = (index % 3) * 0.1 + 's';
                        }}
                    }});
                }}
            }});
        }}, observerOptions);

        // Observe all question cards for reveal animation
        document.addEventListener('DOMContentLoaded', function() {{
            const cards = document.querySelectorAll('.question-card');
            cards.forEach(function(card) {{
                card.classList.add('parallax-layer');
                revealObserver.observe(card);
            }});
        }});

        // Parallax scrolling effect
        let ticking = false;
        window.addEventListener('scroll', function() {{
            if (!ticking) {{
                window.requestAnimationFrame(function() {{
                    const scrolled = window.pageYOffset;
                    const parallaxLayers = document.querySelectorAll('.parallax-layer');
                    
                    parallaxLayers.forEach(function(layer, index) {{
                        const speed = (index % 3 + 1) * 0.05;
                        const yPos = -(scrolled * speed);
                        layer.style.transform = 'translateY(' + yPos + 'px)';
                    }});
                    
                    ticking = false;
                }});
                ticking = true;
            }}
        }});

        // Create starfield
        function createStarfield() {{
            const starfield = document.createElement('div');
            starfield.className = 'starfield';
            
            // Create stars
            for (let i = 0; i < 100; i++) {{
                const star = document.createElement('div');
                star.className = 'star';
                
                // Random position
                star.style.left = Math.random() * 100 + '%';
                star.style.top = Math.random() * 100 + '%';
                
                // Random size (1-3px)
                const size = Math.random() * 2 + 1;
                star.style.width = size + 'px';
                star.style.height = size + 'px';
                
                // Random animation delay
                star.style.animationDelay = Math.random() * 3 + 's';
                star.style.animationDuration = (Math.random() * 2 + 2) + 's';
                
                starfield.appendChild(star);
            }}
            
            document.body.insertBefore(starfield, document.body.firstChild);
        }}

        // Initialize starfield
        createStarfield();

        // 3D tilt effect on cards (magnetic cursor)
        document.addEventListener('DOMContentLoaded', function() {{
            const cards = document.querySelectorAll('.question-card');
            
            cards.forEach(function(card) {{
                card.addEventListener('mousemove', function(e) {{
                    const rect = card.getBoundingClientRect();
                    const x = e.clientX - rect.left;
                    const y = e.clientY - rect.top;
                    
                    const centerX = rect.width / 2;
                    const centerY = rect.height / 2;
                    
                    const rotateX = (y - centerY) / 20;
                    const rotateY = (centerX - x) / 20;
                    
                    card.style.transform = 
                        'translateY(-12px) scale(1.03) ' +
                        'rotateX(' + rotateX + 'deg) rotateY(' + rotateY + 'deg)';
                }});
                
                card.addEventListener('mouseleave', function() {{
                    card.style.transform = '';
                }});
            }});
        }});
    </script>
</body>
</html>
""")

    return "".join(html_parts)


def main():
    """Main function to orchestrate HTML generation."""
    print("🚀 Starting index.html generation...")
    print("")

    # Step 1: Parse questions
    print("Step 1: Parsing questions from questions.md")
    questions = parse_questions("questions.md")
    if not questions:
        print("⚠️  Warning: No questions found. Cannot generate HTML.")
        return 1
    print("")

    # Step 2: Parse status badges
    print("Step 2: Parsing status badges from status.md")
    status_badges = parse_status_badges("status.md")
    print("")

    # Step 3: Generate HTML
    print("Step 3: Generating index.html")
    html_content = generate_html(questions, status_badges)
    print(f"✅ Generated HTML with {len(questions)} question cards")
    print("")

    # Step 4: Write to file
    print("Step 4: Writing to index.html")
    try:
        with open("index.html", "w", encoding="utf-8") as f:
            f.write(html_content)
        print("✅ index.html successfully generated!")
    except Exception as e:
        print(f"❌ Error writing index.html: {e}")
        return 1

    print("")
    print("🎉 Done! index.html has been created.")
    print(f"📊 Generated page with {len(questions)} questions")
    return 0


if __name__ == "__main__":
    exit(main())
