#!/usr/bin/env python3
"""
Generate index.html from questions.md and status.md.

This script creates an interactive HTML status page with:
- Questions displayed in visually appealing cards
- Collapsible dropdowns showing status badges for each language
- Smooth animations and modern design
- Mobile-responsive layout
- Accessibility features (ARIA labels, keyboard navigation)

USAGE:
    python3 generate_html.py

HOW IT WORKS:
    1. Reads questions from questions.md
    2. Reads status badges from status.md (generated by update_status.py)
    3. Generates index.html with interactive features
    4. Idempotent - running multiple times produces the same result

The script is designed to be run automatically via GitHub Actions.
"""

import os
import re
from datetime import datetime

# --- CONFIGURATION ---
LANGUAGE_CONFIG = {
    "qbasic": "QBasic",
    "java": "Java",
    "python": "Python",
    "c": "C",
    "cpp": "C++",
    "csharp": "C#",
    "haskell": "Haskell",
    "perl": "Perl",
    "go": "Go",
    "elixir": "Elixir",
    "asm": "Assembly",
    "fortran": "Fortran",
    "lua": "Lua",
    "ruby": "Ruby",
    "vb": "Visual Basic",
    "pwsh": "PowerShell",
    "batch": "Batch",
}

def parse_questions(questions_file="questions.md"):
    """
    Parse questions from questions.md.
    
    Args:
        questions_file: Path to the questions markdown file
        
    Returns:
        List of dictionaries with 'number' and 'text' keys
    """
    questions = []
    
    if not os.path.exists(questions_file):
        print(f"⚠️  Warning: {questions_file} not found.")
        return questions
    
    try:
        with open(questions_file, "r", encoding="utf-8") as f:
            lines = f.readlines()
        
        for line in lines:
            # Pattern to match numbered questions
            # Example: "1. Print "Hello World". <br> [Filename - 0001_hello_world]"
            # Format: question_num. question_text <br> [Filename - ...]
            match = re.match(r'^(\d+)\.\s+(.+?)(?:\s*<br>.*)?$', line)
            
            if match:
                question_num = int(match.group(1))
                question_text = match.group(2).strip()
                
                # Remove HTML tags from question text
                question_text = re.sub(r'<[^>]+>', '', question_text)
                
                questions.append({
                    'number': question_num,
                    'text': question_text
                })
        
        print(f"📊 Parsed {len(questions)} questions from {questions_file}")
        return questions
        
    except Exception as e:
        print(f"❌ Error parsing {questions_file}: {e}")
        return questions

def parse_status_badges(status_file="status.md"):
    """
    Parse status badges from status.md.
    
    Args:
        status_file: Path to the status markdown file
        
    Returns:
        Dictionary mapping question_number -> list of badge HTML/markdown
    """
    status_badges = {}
    
    if not os.path.exists(status_file):
        print(f"⚠️  Warning: {status_file} not found.")
        return status_badges
    
    try:
        with open(status_file, "r", encoding="utf-8") as f:
            lines = f.readlines()
        
        # Find the table section (starts after the header row)
        in_table = False
        languages = list(LANGUAGE_CONFIG.keys())
        
        for line in lines:
            # Skip header and divider rows
            if line.startswith('| #'):
                in_table = True
                continue
            if line.startswith('|:---'):
                continue
            if line.startswith('## Legend'):
                break
                
            if in_table and line.startswith('|'):
                # Parse table row
                cells = [cell.strip() for cell in line.split('|')]
                # Remove empty cells from start/end
                cells = [c for c in cells if c]
                
                if len(cells) >= 2:
                    # First cell is the question number
                    num_match = re.match(r'(\d+)', cells[0])
                    if num_match:
                        question_num = int(num_match.group(1))
                        # Remaining cells are the badges
                        badges = cells[1:]
                        status_badges[question_num] = badges
        
        print(f"📊 Parsed status badges for {len(status_badges)} questions from {status_file}")
        return status_badges
        
    except Exception as e:
        print(f"❌ Error parsing {status_file}: {e}")
        return status_badges

def convert_badge_to_html(badge_md):
    """
    Convert markdown badge to HTML.
    
    Args:
        badge_md: Markdown badge string (e.g., "[![done](...)](link)" or "![missing](...)")
        
    Returns:
        HTML string for the badge
    """
    # Pattern for clickable badge: [![alt](img_url)](link_url)
    clickable_pattern = r'\[\!\[([^\]]*)\]\(([^\)]+)\)\]\(([^\)]+)\)'
    match = re.match(clickable_pattern, badge_md)
    
    if match:
        alt_text = match.group(1)
        img_url = match.group(2)
        link_url = match.group(3)
        return f'<a href="{link_url}" target="_blank"><img src="{img_url}" alt="{alt_text}" class="badge"></a>'
    
    # Pattern for non-clickable badge: ![alt](img_url)
    non_clickable_pattern = r'\!\[([^\]]*)\]\(([^\)]+)\)'
    match = re.match(non_clickable_pattern, badge_md)
    
    if match:
        alt_text = match.group(1)
        img_url = match.group(2)
        return f'<img src="{img_url}" alt="{alt_text}" class="badge">'
    
    return badge_md

def generate_html(questions, status_badges):
    """
    Generate the complete HTML page.
    
    Args:
        questions: List of question dictionaries
        status_badges: Dictionary mapping question numbers to badge lists
        
    Returns:
        String containing the complete HTML
    """
    languages = list(LANGUAGE_CONFIG.values())
    current_year = datetime.now().year
    
    html_parts = []
    
    # HTML header and styles
    html_parts.append('''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Programming Questions & Status</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        :root {
            --primary-color: #2563eb;
            --secondary-color: #1e40af;
            --accent-color: #3b82f6;
            --background: #f8fafc;
            --card-bg: #ffffff;
            --text-primary: #1e293b;
            --text-secondary: #64748b;
            --border-color: #e2e8f0;
            --shadow-sm: 0 1px 2px 0 rgba(0, 0, 0, 0.05);
            --shadow-md: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
            --shadow-lg: 0 10px 15px -3px rgba(0, 0, 0, 0.1);
            --shadow-xl: 0 20px 25px -5px rgba(0, 0, 0, 0.1);
        }
        
        /* Dark mode variables */
        [data-theme="dark"] {
            --primary-color: #60a5fa;
            --secondary-color: #3b82f6;
            --accent-color: #93c5fd;
            --background: #1a1a1a;
            --card-bg: #2d2d2d;
            --text-primary: #e5e7eb;
            --text-secondary: #9ca3af;
            --border-color: #404040;
            --shadow-sm: 0 1px 2px 0 rgba(0, 0, 0, 0.3);
            --shadow-md: 0 4px 6px -1px rgba(0, 0, 0, 0.4);
            --shadow-lg: 0 10px 15px -3px rgba(0, 0, 0, 0.5);
            --shadow-xl: 0 20px 25px -5px rgba(0, 0, 0, 0.6);
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            background: var(--background);
            color: var(--text-primary);
            line-height: 1.6;
            padding: 20px;
            animation: fadeIn 0.5s ease-in;
            transition: background-color 0.3s ease, color 0.3s ease;
        }
        
        @keyframes fadeIn {
            from {
                opacity: 0;
            }
            to {
                opacity: 1;
            }
        }
        
        .container {
            max-width: 1400px;
            margin: 0 auto;
        }
        
        header {
            text-align: center;
            padding: 40px 20px;
            margin-bottom: 40px;
            animation: slideDown 0.6s ease-out;
        }
        
        @keyframes slideDown {
            from {
                transform: translateY(-30px);
                opacity: 0;
            }
            to {
                transform: translateY(0);
                opacity: 1;
            }
        }
        
        h1 {
            font-size: 3rem;
            font-weight: 700;
            color: var(--primary-color);
            margin-bottom: 10px;
            display: flex;
            align-items: center;
            justify-content: center;
            gap: 15px;
        }
        
        .subtitle {
            font-size: 1.25rem;
            color: var(--text-secondary);
            margin-top: 10px;
        }
        
        .questions-grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(350px, 1fr));
            gap: 25px;
            margin-bottom: 40px;
        }
        
        .question-card {
            background: var(--card-bg);
            border-radius: 12px;
            padding: 24px;
            box-shadow: var(--shadow-md);
            transition: all 0.3s ease;
            animation: fadeInUp 0.5s ease-out;
            animation-fill-mode: both;
            border: 1px solid var(--border-color);
        }
        
        @keyframes fadeInUp {
            from {
                transform: translateY(20px);
                opacity: 0;
            }
            to {
                transform: translateY(0);
                opacity: 1;
            }
        }
        
        .question-card:hover {
            transform: translateY(-5px);
            box-shadow: var(--shadow-xl);
            border-color: var(--accent-color);
        }
        
        .question-number {
            display: inline-block;
            background: linear-gradient(135deg, var(--primary-color), var(--secondary-color));
            color: white;
            padding: 6px 14px;
            border-radius: 20px;
            font-weight: 600;
            font-size: 0.875rem;
            margin-bottom: 12px;
        }
        
        .question-text {
            font-size: 1.05rem;
            color: var(--text-primary);
            margin-bottom: 16px;
            line-height: 1.6;
        }
        
        .status-toggle {
            background: none;
            border: none;
            width: 100%;
            text-align: left;
            padding: 12px 16px;
            background: var(--background);
            border-radius: 8px;
            cursor: pointer;
            font-size: 1rem;
            font-weight: 600;
            color: var(--primary-color);
            display: flex;
            align-items: center;
            justify-content: space-between;
            transition: all 0.2s ease;
        }
        
        .status-toggle:hover {
            background: #e0e7ff;
        }
        
        .status-toggle:focus {
            outline: 2px solid var(--accent-color);
            outline-offset: 2px;
        }
        
        .arrow {
            transition: transform 0.3s ease;
            font-size: 1.2rem;
        }
        
        .arrow.open {
            transform: rotate(180deg);
        }
        
        .status-content {
            max-height: 0;
            overflow: hidden;
            transition: max-height 0.4s ease;
        }
        
        .status-content.open {
            max-height: 1000px;
        }
        
        .status-table-wrapper {
            padding: 16px 0;
            animation: fadeIn 0.3s ease;
        }
        
        .status-table {
            width: 100%;
            overflow-x: auto;
            margin-top: 12px;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 0.875rem;
        }
        
        th {
            background: var(--background);
            padding: 8px 4px;
            text-align: center;
            font-weight: 600;
            color: var(--text-secondary);
            border-bottom: 2px solid var(--border-color);
            font-size: 0.8rem;
        }
        
        td {
            padding: 8px 4px;
            text-align: center;
            border-bottom: 1px solid var(--border-color);
        }
        
        .badge {
            height: 20px;
            display: inline-block;
            vertical-align: middle;
        }
        
        footer {
            text-align: center;
            padding: 40px 20px;
            color: var(--text-secondary);
            font-size: 0.875rem;
            border-top: 1px solid var(--border-color);
            margin-top: 60px;
        }
        
        footer a {
            color: var(--primary-color);
            text-decoration: none;
        }
        
        footer a:hover {
            text-decoration: underline;
        }
        
        /* Theme Toggle Button */
        .theme-toggle {
            position: fixed;
            top: 20px;
            right: 20px;
            background: var(--card-bg);
            border: 2px solid var(--border-color);
            border-radius: 50%;
            width: 50px;
            height: 50px;
            display: flex;
            align-items: center;
            justify-content: center;
            cursor: pointer;
            font-size: 1.5rem;
            box-shadow: var(--shadow-md);
            transition: all 0.3s ease;
            z-index: 1000;
        }
        
        .theme-toggle:hover {
            transform: scale(1.1);
            box-shadow: var(--shadow-lg);
        }
        
        .theme-toggle:active {
            transform: scale(0.95);
        }
        
        /* Badge Tip Section */
        .badge-tip {
            background: linear-gradient(135deg, #fef3c7 0%, #fde68a 100%);
            border-left: 4px solid #f59e0b;
            padding: 16px 20px;
            border-radius: 8px;
            margin-bottom: 40px;
            display: flex;
            align-items: center;
            gap: 12px;
            box-shadow: var(--shadow-sm);
            animation: slideDown 0.6s ease-out;
        }
        
        [data-theme="dark"] .badge-tip {
            background: linear-gradient(135deg, #422006 0%, #713f12 100%);
            border-left-color: #f59e0b;
        }
        
        .badge-tip-icon {
            font-size: 1.5rem;
            flex-shrink: 0;
        }
        
        .badge-tip-text {
            color: #78350f;
            font-weight: 500;
            font-size: 1rem;
        }
        
        [data-theme="dark"] .badge-tip-text {
            color: #fde68a;
        }
        
        @media (max-width: 768px) {
            h1 {
                font-size: 2rem;
                flex-direction: column;
                gap: 10px;
            }
            
            .questions-grid {
                grid-template-columns: 1fr;
                gap: 20px;
            }
            
            .question-card {
                padding: 20px;
            }
            
            th, td {
                padding: 6px 2px;
                font-size: 0.75rem;
            }
            
            .splash-title {
                font-size: 2rem;
            }
            
            .splash-subtitle {
                font-size: 0.9rem;
            }
            
            .theme-toggle {
                width: 45px;
                height: 45px;
                font-size: 1.3rem;
            }
        }
        
        /* Stagger animation for cards */
        ''')
    
    # Add staggered animation delays for cards
    for i in range(min(len(questions), 100)):
        delay = i * 0.03
        html_parts.append(f'        .question-card:nth-child({i+1}) {{ animation-delay: {delay}s; }}\n')
    
    html_parts.append('''        
        /* Splash Screen Styles */
        #splash-screen {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            z-index: 9999;
            animation: splashFadeIn 0.6s ease-out;
        }
        
        #splash-screen.hidden {
            animation: splashFadeOut 0.6s ease-out forwards;
        }
        
        @keyframes splashFadeIn {
            from {
                opacity: 0;
            }
            to {
                opacity: 1;
            }
        }
        
        @keyframes splashFadeOut {
            from {
                opacity: 1;
            }
            to {
                opacity: 0;
                visibility: hidden;
            }
        }
        
        .splash-content {
            text-align: center;
            color: white;
            animation: splashContentFade 0.8s ease-out;
        }
        
        @keyframes splashContentFade {
            from {
                opacity: 0;
                transform: translateY(20px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }
        
        .splash-title {
            font-size: 3.5rem;
            font-weight: 300;
            margin-bottom: 10px;
            letter-spacing: 2px;
            font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
        }
        
        .splash-subtitle {
            font-size: 1.1rem;
            opacity: 0.85;
            font-weight: 300;
            letter-spacing: 1px;
        }
    </style>
</head>
<body>
    <!-- Splash Screen -->
    <div id="splash-screen">
        <div class="splash-content">
            <h1 class="splash-title">Programming Questions</h1>
            <p class="splash-subtitle">Building your progress tracker</p>
        </div>
    </div>
    
    <!-- Theme Toggle Button -->
    <button class="theme-toggle" onclick="toggleTheme()" aria-label="Toggle dark mode">
        <span id="theme-icon">🌙</span>
    </button>
    
    <div class="container">
        <header>
            <h1>
                <span>📘</span>
                <span>Programming Questions & Status</span>
            </h1>
        </header>
        
        <!-- Badge Tip -->
        <div class="badge-tip">
            <div class="badge-tip-icon">💡</div>
            <div class="badge-tip-text">Tip: Click on the badges to view the code</div>
        </div>
        
        <div class="questions-grid">
''')
    
    # Generate question cards
    for question in questions:
        qnum = question['number']
        qtext = question['text']
        badges = status_badges.get(qnum, [])
        
        html_parts.append(f'''            <div class="question-card">
                <div class="question-number">#{qnum:04d}</div>
                <div class="question-text">{qtext}</div>
                <button class="status-toggle" 
                        aria-expanded="false" 
                        aria-controls="status-{qnum}"
                        onclick="toggleStatus({qnum})">
                    <span>Status</span>
                    <span class="arrow" id="arrow-{qnum}">▼</span>
                </button>
                <div class="status-content" id="status-{qnum}" role="region" aria-hidden="true">
                    <div class="status-table-wrapper">
                        <div class="status-table">
                            <table>
                                <thead>
                                    <tr>
''')
        
        # Add language headers
        for lang in languages:
            html_parts.append(f'                                        <th>{lang}</th>\n')
        
        html_parts.append('''                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
''')
        
        # Add badges for each language
        for badge_md in badges[:len(languages)]:  # Ensure we don't exceed language count
            badge_html = convert_badge_to_html(badge_md)
            html_parts.append(f'                                        <td>{badge_html}</td>\n')
        
        # Fill remaining cells if needed
        for _ in range(len(languages) - len(badges)):
            html_parts.append('                                        <td>-</td>\n')
        
        html_parts.append('''                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
''')
    
    # Add footer and JavaScript
    html_parts.append(f'''        </div>
        
        <footer>
            <p>Generated on {datetime.now().strftime("%B %d, %Y at %H:%M UTC")}</p>
            <p>
                <a href="https://github.com/DibyajyotiBiswal57/programs" target="_blank">View on GitHub</a>
            </p>
            <p>&copy; {current_year} Programming Questions Project</p>
        </footer>
    </div>
    
    <script>
        // Theme Toggle Functionality
        function toggleTheme() {{
            const currentTheme = document.documentElement.getAttribute('data-theme');
            const newTheme = currentTheme === 'dark' ? 'light' : 'dark';
            
            document.documentElement.setAttribute('data-theme', newTheme);
            localStorage.setItem('theme', newTheme);
            
            // Update icon
            const themeIcon = document.getElementById('theme-icon');
            themeIcon.textContent = newTheme === 'dark' ? '☀️' : '🌙';
        }}
        
        // Load saved theme on page load
        (function() {{
            const savedTheme = localStorage.getItem('theme') || 'light';
            document.documentElement.setAttribute('data-theme', savedTheme);
            
            // Set initial icon
            const themeIcon = document.getElementById('theme-icon');
            if (themeIcon) {{
                themeIcon.textContent = savedTheme === 'dark' ? '☀️' : '🌙';
            }}
        }})();
        
        function toggleStatus(questionNumber) {{
            const content = document.getElementById('status-' + questionNumber);
            const arrow = document.getElementById('arrow-' + questionNumber);
            const button = content.previousElementSibling;
            
            const isOpen = content.classList.contains('open');
            
            if (isOpen) {{
                content.classList.remove('open');
                arrow.classList.remove('open');
                button.setAttribute('aria-expanded', 'false');
                content.setAttribute('aria-hidden', 'true');
            }} else {{
                content.classList.add('open');
                arrow.classList.add('open');
                button.setAttribute('aria-expanded', 'true');
                content.setAttribute('aria-hidden', 'false');
            }}
        }}
        
        // Keyboard navigation support
        document.addEventListener('keydown', function(event) {{
            if (event.target.classList.contains('status-toggle')) {{
                if (event.key === 'Enter' || event.key === ' ') {{
                    event.preventDefault();
                    event.target.click();
                }}
            }}
        }});
        
        // Splash screen initialization
        window.addEventListener('load', function() {{
            // Wait for a minimum time to show the splash screen (2.5 seconds)
            setTimeout(function() {{
                const splashScreen = document.getElementById('splash-screen');
                splashScreen.classList.add('hidden');
                
                // Remove the splash screen from DOM after animation completes
                setTimeout(function() {{
                    splashScreen.remove();
                }}, 600); // Match the fade-out animation duration
            }}, 2500);
        }});
    </script>
</body>
</html>
''')
    
    return ''.join(html_parts)

def main():
    """Main function to orchestrate HTML generation."""
    print("🚀 Starting index.html generation...")
    print("")
    
    # Step 1: Parse questions
    print("Step 1: Parsing questions from questions.md")
    questions = parse_questions("questions.md")
    if not questions:
        print("⚠️  Warning: No questions found. Cannot generate HTML.")
        return 1
    print("")
    
    # Step 2: Parse status badges
    print("Step 2: Parsing status badges from status.md")
    status_badges = parse_status_badges("status.md")
    print("")
    
    # Step 3: Generate HTML
    print("Step 3: Generating index.html")
    html_content = generate_html(questions, status_badges)
    print(f"✅ Generated HTML with {len(questions)} question cards")
    print("")
    
    # Step 4: Write to file
    print("Step 4: Writing to index.html")
    try:
        with open("index.html", "w", encoding="utf-8") as f:
            f.write(html_content)
        print("✅ index.html successfully generated!")
    except Exception as e:
        print(f"❌ Error writing index.html: {e}")
        return 1
    
    print("")
    print("🎉 Done! index.html has been created.")
    print(f"📊 Generated page with {len(questions)} questions")
    return 0


if __name__ == "__main__":
    exit(main())
