#!/usr/bin/env python3
"""
Generate index.html from questions.md and status.md.

This script creates an interactive HTML status page with:
- Questions displayed in visually appealing cards
- Collapsible dropdowns showing status badges for each language
- Smooth animations and modern design
- Mobile-responsive layout
- Accessibility features (ARIA labels, keyboard navigation)

USAGE:
    python3 generate_html.py

HOW IT WORKS:
    1. Reads questions from questions.md
    2. Reads status badges from status.md (generated by update_status.py)
    3. Generates index.html with interactive features
    4. Idempotent - running multiple times produces the same result

The script is designed to be run automatically via GitHub Actions.
"""

import os
import re
from datetime import datetime

# --- CONFIGURATION ---
LANGUAGE_CONFIG = {
    "qbasic": "QBasic",
    "java": "Java",
    "python": "Python",
    "c": "C",
    "cpp": "C++",
    "csharp": "C#",
    "haskell": "Haskell",
    "perl": "Perl",
    "go": "Go",
    "elixir": "Elixir",
    "asm": "Assembly",
    "fortran": "Fortran",
    "lua": "Lua",
    "ruby": "Ruby",
    "vb": "Visual Basic",
    "pwsh": "PowerShell",
    "batch": "Batch",
}


def parse_questions(questions_file="questions.md"):
    """
    Parse questions from questions.md.

    Args:
        questions_file: Path to the questions markdown file

    Returns:
        List of dictionaries with 'number' and 'text' keys
    """
    questions = []

    if not os.path.exists(questions_file):
        print(f"⚠️  Warning: {questions_file} not found.")
        return questions

    try:
        with open(questions_file, "r", encoding="utf-8") as f:
            lines = f.readlines()

        for line in lines:
            # Pattern to match numbered questions
            # Example: "1. Print "Hello World". <br> [Filename - 0001_hello_world]"
            # Format: question_num. question_text <br> [Filename - ...]
            match = re.match(r"^(\d+)\.\s+(.+?)(?:\s*<br>.*)?$", line)

            if match:
                question_num = int(match.group(1))
                question_text = match.group(2).strip()

                # Remove HTML tags from question text
                question_text = re.sub(r"<[^>]+>", "", question_text)

                questions.append(
                    {"number": question_num, "text": question_text})

        print(f"📊 Parsed {len(questions)} questions from {questions_file}")
        return questions

    except Exception as e:
        print(f"❌ Error parsing {questions_file}: {e}")
        return questions


def parse_status_badges(status_file="status.md"):
    """
    Parse status badges from status.md.

    Args:
        status_file: Path to the status markdown file

    Returns:
        Dictionary mapping question_number -> list of badge HTML/markdown
    """
    status_badges = {}

    if not os.path.exists(status_file):
        print(f"⚠️  Warning: {status_file} not found.")
        return status_badges

    try:
        with open(status_file, "r", encoding="utf-8") as f:
            lines = f.readlines()

        # Find the table section (starts after the header row)
        in_table = False
        languages = list(LANGUAGE_CONFIG.keys())

        for line in lines:
            # Skip header and divider rows
            if line.startswith("| #"):
                in_table = True
                continue
            if line.startswith("|:---"):
                continue
            if line.startswith("## Legend"):
                break

            if in_table and line.startswith("|"):
                # Parse table row
                cells = [cell.strip() for cell in line.split("|")]
                # Remove empty cells from start/end
                cells = [c for c in cells if c]

                if len(cells) >= 2:
                    # First cell is the question number
                    num_match = re.match(r"(\d+)", cells[0])
                    if num_match:
                        question_num = int(num_match.group(1))
                        # Remaining cells are the badges
                        badges = cells[1:]
                        status_badges[question_num] = badges

        print(f"📊 Parsed status badges for {
            len(status_badges)} questions from {status_file}")
        return status_badges

    except Exception as e:
        print(f"❌ Error parsing {status_file}: {e}")
        return status_badges


def convert_badge_to_html(badge_md):
    """
    Convert markdown badge to HTML.

    Args:
        badge_md: Markdown badge string (e.g., "[![done](...)](link)" or "![missing](...)")

    Returns:
        HTML string for the badge
    """
    # Pattern for clickable badge: [![alt](img_url)](link_url)
    clickable_pattern = r"\[\!\[([^\]]*)\]\(([^\)]+)\)\]\(([^\)]+)\)"
    match = re.match(clickable_pattern, badge_md)

    if match:
        alt_text = match.group(1)
        img_url = match.group(2)
        link_url = match.group(3)
        return f'<a href="{link_url}" target="_blank"><img src="{img_url}" alt="{alt_text}" class="badge"></a>'

    # Pattern for non-clickable badge: ![alt](img_url)
    non_clickable_pattern = r"\!\[([^\]]*)\]\(([^\)]+)\)"
    match = re.match(non_clickable_pattern, badge_md)

    if match:
        alt_text = match.group(1)
        img_url = match.group(2)
        return f'<img src="{img_url}" alt="{alt_text}" class="badge">'

    return badge_md


def generate_html(questions, status_badges):
    """
    Generate the complete HTML page.

    Args:
        questions: List of question dictionaries
        status_badges: Dictionary mapping question numbers to badge lists

    Returns:
        String containing the complete HTML
    """
    languages = list(LANGUAGE_CONFIG.values())
    current_year = datetime.now().year

    html_parts = []

    # HTML header and styles
    html_parts.append("""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Programming Questions & Status</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        :root {
            --primary-color: #2563eb;
            --secondary-color: #1e40af;
            --accent-color: #3b82f6;
            --background: #f8fafc;
            --card-bg: #ffffff;
            --text-primary: #1e293b;
            --text-secondary: #64748b;
            --border-color: #e2e8f0;
            --shadow-sm: 0 1px 2px 0 rgba(0, 0, 0, 0.05);
            --shadow-md: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
            --shadow-lg: 0 10px 15px -3px rgba(0, 0, 0, 0.1);
            --shadow-xl: 0 20px 25px -5px rgba(0, 0, 0, 0.1);
        }

        /* Dark mode variables */
        [data-theme="dark"] {
            --primary-color: #60a5fa;
            --secondary-color: #3b82f6;
            --accent-color: #93c5fd;
            --background: #1a1a1a;
            --card-bg: #2d2d2d;
            --text-primary: #e5e7eb;
            --text-secondary: #9ca3af;
            --border-color: #404040;
            --shadow-sm: 0 1px 2px 0 rgba(0, 0, 0, 0.3);
            --shadow-md: 0 4px 6px -1px rgba(0, 0, 0, 0.4);
            --shadow-lg: 0 10px 15px -3px rgba(0, 0, 0, 0.5);
            --shadow-xl: 0 20px 25px -5px rgba(0, 0, 0, 0.6);
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            background: linear-gradient(-45deg, #a8e6cf, #7ec8e3, #56c9d8, #89e5d0);
            background-size: 400% 400%;
            animation: gradientShift 15s ease infinite, fadeIn 0.5s ease-in;
            color: var(--text-primary);
            line-height: 1.6;
            padding: 20px;
            transition: color 0.3s ease;
            position: relative;
            min-height: 100vh;
        }

        [data-theme="dark"] body {
            background: linear-gradient(-45deg, #0a1f1f, #0d2b3e, #0f3a4a, #1a4d5c);
            background-size: 400% 400%;
            animation: gradientShift 15s ease infinite, fadeIn 0.5s ease-in;
        }

        @keyframes gradientShift {
            0% {
                background-position: 0% 50%;
            }
            50% {
                background-position: 100% 50%;
            }
            100% {
                background-position: 0% 50%;
            }
        }

        @keyframes fadeIn {
            from {
                opacity: 0;
            }
            to {
                opacity: 1;
            }
        }

        .container {
            max-width: 1400px;
            margin: 0 auto;
            padding: 0 8px;
        }

        header {
            text-align: center;
            padding: 40px 20px;
            margin-bottom: 40px;
            animation: slideDown 0.6s ease-out;
        }

        @keyframes slideDown {
            from {
                transform: translateY(-30px);
                opacity: 0;
            }
            to {
                transform: translateY(0);
                opacity: 1;
            }
        }

        h1 {
            font-size: 3rem;
            font-weight: 700;
            color: var(--primary-color);
            margin-bottom: 10px;
            display: flex;
            align-items: center;
            justify-content: center;
            gap: 15px;
        }

        .subtitle {
            font-size: 1.25rem;
            color: var(--text-secondary);
            margin-top: 10px;
        }

        .questions-grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
            gap: 25px;
            margin-bottom: 40px;
        }

        .question-card {
            background: var(--card-bg);
            border-radius: 12px;
            padding: 24px;
            box-shadow: var(--shadow-md);
            transition: all 0.3s ease;
            animation: fadeInUp 0.5s ease-out;
            animation-fill-mode: both;
            border: 1px solid var(--border-color);
        }

        @keyframes fadeInUp {
            from {
                transform: translateY(20px);
                opacity: 0;
            }
            to {
                transform: translateY(0);
                opacity: 1;
            }
        }

        .question-card:hover {
            transform: translateY(-5px);
            box-shadow: var(--shadow-xl);
            border-color: var(--accent-color);
        }

        .question-number {
            display: inline-block;
            background: linear-gradient(135deg, var(--primary-color), var(--secondary-color));
            color: white;
            padding: 6px 14px;
            border-radius: 20px;
            font-weight: 600;
            font-size: 0.875rem;
            margin-bottom: 12px;
        }

        .question-text {
            font-size: 1.05rem;
            color: var(--text-primary);
            margin-bottom: 16px;
            line-height: 1.6;
        }

        .status-toggle {
            background: none;
            border: none;
            width: 100%;
            text-align: left;
            padding: 12px 16px;
            background: var(--background);
            border-radius: 8px;
            cursor: pointer;
            font-size: 1rem;
            font-weight: 600;
            color: var(--primary-color);
            display: flex;
            align-items: center;
            justify-content: space-between;
            transition: all 0.2s ease;
        }

        .status-toggle:hover {
            background: #e0e7ff;
        }

        .status-toggle:focus {
            outline: 2px solid var(--accent-color);
            outline-offset: 2px;
        }

        .arrow {
            transition: transform 0.3s ease;
            font-size: 1.2rem;
        }

        .arrow.open {
            transform: rotate(180deg);
        }

        .status-content {
            max-height: 0;
            overflow: hidden;
            transition: max-height 0.4s ease;
        }

        .status-content.open {
            max-height: 1000px;
        }

        .status-table-wrapper {
            padding: 16px 0;
            animation: fadeIn 0.3s ease;
        }

        .status-table {
            width: 100%;
            overflow-x: auto;
            margin-top: 12px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 0.875rem;
        }

        th {
            background: var(--background);
            padding: 8px 4px;
            text-align: center;
            font-weight: 600;
            color: var(--text-secondary);
            border-bottom: 2px solid var(--border-color);
            font-size: 0.8rem;
        }

        td {
            padding: 8px 4px;
            text-align: center;
            border-bottom: 1px solid var(--border-color);
        }

        .badge {
            height: 20px;
            display: inline-block;
            vertical-align: middle;
        }

        footer {
            text-align: center;
            padding: 40px 20px;
            color: var(--text-secondary);
            font-size: 0.875rem;
            border-top: 1px solid var(--border-color);
            margin-top: 60px;
        }

        footer a {
            color: var(--primary-color);
            text-decoration: none;
        }

        footer a:hover {
            text-decoration: underline;
        }

        /* Theme Toggle Button */
        .theme-toggle {
            position: fixed;
            top: 20px;
            right: 20px;
            background: var(--card-bg);
            border: 2px solid var(--border-color);
            border-radius: 50%;
            width: 50px;
            height: 50px;
            display: flex;
            align-items: center;
            justify-content: center;
            cursor: pointer;
            font-size: 1.5rem;
            box-shadow: var(--shadow-md);
            transition: all 0.3s ease;
            z-index: 1000;
        }

        .theme-toggle:hover {
            transform: scale(1.1);
            box-shadow: var(--shadow-lg);
        }

        .theme-toggle:active {
            transform: scale(0.95);
        }

        /* Search Box */
        .search-container {
            max-width: 600px;
            margin: 0 auto 40px auto;
            animation: slideDown 0.6s ease-out;
        }

        .search-box {
            position: relative;
            width: 100%;
        }

        .search-input {
            width: 100%;
            padding: 16px 50px 16px 50px;
            font-size: 1.05rem;
            border: 2px solid var(--border-color);
            border-radius: 12px;
            background: var(--card-bg);
            color: var(--text-primary);
            outline: none;
            transition: all 0.3s ease;
            box-shadow: var(--shadow-sm);
        }

        .search-input:focus {
            border-color: var(--primary-color);
            box-shadow: 0 0 0 3px rgba(37, 99, 235, 0.1);
        }

        [data-theme="dark"] .search-input:focus {
            box-shadow: 0 0 0 3px rgba(96, 165, 250, 0.2);
        }

        .search-input::placeholder {
            color: var(--text-secondary);
        }

        .search-icon {
            position: absolute;
            left: 18px;
            top: 50%;
            transform: translateY(-50%);
            font-size: 1.3rem;
            color: var(--text-secondary);
            pointer-events: none;
        }

        .clear-search {
            position: absolute;
            right: 18px;
            top: 50%;
            transform: translateY(-50%);
            background: none;
            border: none;
            font-size: 1.3rem;
            color: var(--text-secondary);
            cursor: pointer;
            padding: 4px;
            opacity: 0;
            transition: opacity 0.2s ease;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .clear-search.visible {
            opacity: 1;
        }

        .clear-search:hover {
            color: var(--text-primary);
        }

        .search-results-info {
            text-align: center;
            margin-top: 12px;
            font-size: 0.95rem;
            color: var(--text-secondary);
        }

        .no-results {
            text-align: center;
            padding: 60px 20px;
            color: var(--text-secondary);
            font-size: 1.1rem;
        }

        .no-results-icon {
            font-size: 3rem;
            margin-bottom: 16px;
        }

        .question-card.hidden {
            display: none;
        }

        /* Badge Tip Section */
        .badge-tip {
            background: linear-gradient(135deg, #fef3c7 0%, #fde68a 100%);
            border-left: 4px solid #f59e0b;
            padding: 16px 20px;
            border-radius: 8px;
            margin-bottom: 40px;
            display: flex;
            align-items: center;
            gap: 12px;
            box-shadow: var(--shadow-sm);
            animation: slideDown 0.6s ease-out;
        }

        [data-theme="dark"] .badge-tip {
            background: linear-gradient(135deg, #422006 0%, #713f12 100%);
            border-left-color: #f59e0b;
        }

        .badge-tip-icon {
            font-size: 1.5rem;
            flex-shrink: 0;
        }

        .badge-tip-text {
            color: #78350f;
            font-weight: 500;
            font-size: 1rem;
        }

        [data-theme="dark"] .badge-tip-text {
            color: #fde68a;
        }

        @media (max-width: 768px) {
            body {
                padding: 12px;
                line-height: 1.5;
            }

            h1 {
                font-size: 1.75rem;
                flex-direction: column;
                gap: 8px;
            }

            .subtitle {
                font-size: 1rem;
                margin-top: 8px;
            }

            header {
                padding: 24px 12px;
                margin-bottom: 24px;
            }

            .questions-grid {
                grid-template-columns: 1fr;
                gap: 16px;
            }

            .question-card {
                padding: 16px;
                border-radius: 8px;
            }

            .question-number {
                padding: 5px 12px;
                font-size: 0.8rem;
                margin-bottom: 10px;
            }

            .question-text {
                font-size: 0.95rem;
                line-height: 1.5;
            }

            .status-header {
                padding: 12px 16px;
                font-size: 0.9rem;
                min-height: 48px;
            }

            .status-icon {
                font-size: 1rem;
            }

            .status-count {
                font-size: 0.8rem;
            }

            .status-table-wrapper {
                padding: 12px 0;
            }

            th, td {
                padding: 8px 4px;
                font-size: 0.7rem;
            }

            th {
                font-size: 0.65rem;
            }

            .search-container {
                margin-bottom: 24px;
            }

            .search-input {
                padding: 14px 44px 14px 44px;
                font-size: 1rem;
                border-radius: 10px;
            }

            .search-icon {
                font-size: 1.2rem;
                left: 14px;
            }

            .clear-search {
                font-size: 1.2rem;
                right: 14px;
            }

            .splash-title {
                font-size: 1.5rem;
            }

            .splash-subtitle {
                font-size: 0.85rem;
            }

            .theme-toggle {
                width: 52px;
                height: 52px;
                font-size: 1.4rem;
                top: 12px;
                right: 12px;
            }

            footer {
                padding: 24px 12px;
                margin-top: 40px;
                font-size: 0.8rem;
            }

            .badge-tip {
                padding: 12px;
                margin: 12px 16px;
                font-size: 0.85rem;
            }

            .badge-tip-icon {
                font-size: 1.2rem;
            }

            .badge-tip-text {
                font-size: 0.85rem;
            }
        }

        /* Additional mobile improvements for very small screens */
        @media (max-width: 480px) {
            body {
                padding: 8px;
            }

            h1 {
                font-size: 1.5rem;
            }

            .subtitle {
                font-size: 0.9rem;
            }

            header {
                padding: 20px 8px;
                margin-bottom: 20px;
            }

            .questions-grid {
                gap: 12px;
            }

            .question-card {
                padding: 14px;
            }

            .question-text {
                font-size: 0.9rem;
            }

            .search-input {
                padding: 12px 40px 12px 40px;
                font-size: 0.95rem;
            }

            .theme-toggle {
                width: 48px;
                height: 48px;
                font-size: 1.3rem;
                top: 8px;
                right: 8px;
            }

            .status-header {
                padding: 10px 14px;
                font-size: 0.85rem;
                min-height: 44px;
            }

            th, td {
                padding: 6px 2px;
                font-size: 0.65rem;
            }

            th {
                font-size: 0.6rem;
            }
        }

        /* Stagger animation for cards */
        """)

    # Add staggered animation delays for cards
    for i in range(min(len(questions), 100)):
        delay = i * 0.03
        html_parts.append(
            f"        .question-card:nth-child({i + 1}) {{ animation-delay: {delay}s; }}\n"
        )

    html_parts.append("""
        /* Splash Screen Styles - Linux Boot Style */
        #splash-screen {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%);
            display: flex;
            flex-direction: column;
            align-items: flex-start;
            justify-content: flex-start;
            padding: 40px;
            z-index: 9999;
            overflow: hidden;
            font-family: 'Courier New', Consolas, Monaco, monospace;
        }

        #splash-screen.hidden {
            animation: splashFadeOut 0.6s ease-out forwards;
        }

        @keyframes splashFadeOut {
            from {
                opacity: 1;
            }
            to {
                opacity: 0;
                visibility: hidden;
            }
        }

        .boot-line {
            color: #00ff00;
            font-size: 0.9rem;
            line-height: 1.6;
            margin: 2px 0;
            opacity: 0;
            animation: bootLineAppear 0.1s ease-out forwards;
        }

        @keyframes bootLineAppear {
            from {
                opacity: 0;
                transform: translateX(-5px);
            }
            to {
                opacity: 1;
                transform: translateX(0);
            }
        }

        .boot-line.info {
            color: #00d4ff;
        }

        .boot-line.warning {
            color: #ffaa00;
        }

        .boot-line.highlight {
            color: #ffffff;
            font-weight: bold;
        }

        .boot-cursor {
            display: inline-block;
            width: 10px;
            height: 16px;
            background: #00ff00;
            margin-left: 5px;
            animation: cursorBlink 1s infinite;
        }

        @keyframes cursorBlink {
            0%, 49% {
                opacity: 1;
            }
            50%, 100% {
                opacity: 0;
            }
        }
    </style>
</head>
<body>
    <!-- Splash Screen - Linux Boot Style -->
    <div id="splash-screen">
        <div class="boot-line" style="animation-delay: 0.05s;">[  OK  ] Starting Programming Questions Bootloader...</div>
        <div class="boot-line info" style="animation-delay: 0.15s;">Initializing system modules...</div>
        <div class="boot-line" style="animation-delay: 0.30s;">[  OK  ] Mounted /dev/sda1 on /questions</div>
        <div class="boot-line" style="animation-delay: 0.45s;">[  OK  ] Started Language Runtime Services</div>
        <div class="boot-line info" style="animation-delay: 0.60s;">Loading Python modules... Done.</div>
        <div class="boot-line info" style="animation-delay: 0.75s;">Loading Java modules... Done.</div>
        <div class="boot-line info" style="animation-delay: 0.90s;">Loading C/C++ modules... Done.</div>
        <div class="boot-line" style="animation-delay: 1.05s;">[  OK  ] Started Progress Tracking Service</div>
        <div class="boot-line" style="animation-delay: 1.20s;">[  OK  ] Reached target Multi-Language Support</div>
        <div class="boot-line warning" style="animation-delay: 1.35s;">Checking status badges... 90 questions found.</div>
        <div class="boot-line" style="animation-delay: 1.50s;">[  OK  ] Started Dark Mode Theme Service</div>
        <div class="boot-line" style="animation-delay: 1.65s;">[  OK  ] Started Web Interface</div>
        <div class="boot-line highlight" style="animation-delay: 1.80s;"><br>Programming Questions v1.0 - Ready</div>
        <div class="boot-line info" style="animation-delay: 1.95s;">System boot complete. Starting interface...<span class="boot-cursor"></span></div>
    </div>

    <!-- Theme Toggle Button -->
    <button class="theme-toggle" onclick="toggleTheme()" aria-label="Toggle dark mode">
        <span id="theme-icon">🌙</span>
    </button>

    <div class="container">
        <header>
            <h1>
                <span>📘</span>
                <span>Programming Questions & Status</span>
            </h1>
        </header>

        <!-- Search Box -->
        <div class="search-container">
            <div class="search-box">
                <span class="search-icon">🔍</span>
                <input 
                    type="text" 
                    id="searchInput" 
                    class="search-input" 
                    placeholder="Search questions by number or description..."
                    aria-label="Search questions"
                    autocomplete="off"
                >
                <button 
                    id="clearSearch" 
                    class="clear-search" 
                    aria-label="Clear search"
                    onclick="clearSearch()"
                >✕</button>
            </div>
            <div id="searchResultsInfo" class="search-results-info"></div>
        </div>

        <!-- Badge Tip -->
        <div class="badge-tip">
            <div class="badge-tip-icon">💡</div>
            <div class="badge-tip-text">Tip: Click on the badges to view the code</div>
        </div>

        <div id="noResults" class="no-results" style="display: none;">
            <div class="no-results-icon">🔍</div>
            <div>No questions found matching your search.</div>
        </div>

        <div class="questions-grid" id="questionsGrid">
""")

    # Generate question cards
    for question in questions:
        qnum = question["number"]
        qtext = question["text"]
        badges = status_badges.get(qnum, [])

        html_parts.append(f"""            <div class="question-card">
                <div class="question-number">#{qnum:04d}</div>
                <div class="question-text">{qtext}</div>
                <button class="status-toggle"
                        aria-expanded="false"
                        aria-controls="status-{qnum}"
                        onclick="toggleStatus({qnum})">
                    <span>Status</span>
                    <span class="arrow" id="arrow-{qnum}">▼</span>
                </button>
                <div class="status-content" id="status-{qnum}" role="region" aria-hidden="true">
                    <div class="status-table-wrapper">
                        <div class="status-table">
                            <table>
                                <thead>
                                    <tr>
""")

        # Add language headers
        for lang in languages:
            html_parts.append(
                f"                                        <th>{lang}</th>\n"
            )

        html_parts.append("""                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
""")

        # Add badges for each language
        for badge_md in badges[
            : len(languages)
        ]:  # Ensure we don't exceed language count
            badge_html = convert_badge_to_html(badge_md)
            html_parts.append(
                f"                                        <td>{badge_html}</td>\n")

        # Fill remaining cells if needed
        for _ in range(len(languages) - len(badges)):
            html_parts.append(
                "                                        <td>-</td>\n")

        html_parts.append("""                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
""")

    # Add footer and JavaScript
    html_parts.append(f"""        </div>

        <footer>
            <p>Generated on {datetime.now().strftime("%B %d, %Y at %H:%M UTC")}</p>
            <p>
                <a href="https://github.com/DibyajyotiBiswal57/programs" target="_blank">View on GitHub</a>
            </p>
            <p>&copy; {current_year} Programming Questions Project</p>
        </footer>
    </div>

    <script>
        // Theme Toggle Functionality
        function toggleTheme() {{
            const currentTheme = document.documentElement.getAttribute('data-theme');
            const newTheme = currentTheme === 'dark' ? 'light' : 'dark';

            document.documentElement.setAttribute('data-theme', newTheme);
            localStorage.setItem('theme', newTheme);

            // Update icon
            const themeIcon = document.getElementById('theme-icon');
            themeIcon.textContent = newTheme === 'dark' ? '☀️' : '🌙';
        }}

        // Load saved theme on page load
        (function() {{
            const savedTheme = localStorage.getItem('theme') || 'light';
            document.documentElement.setAttribute('data-theme', savedTheme);

            // Set initial icon
            const themeIcon = document.getElementById('theme-icon');
            if (themeIcon) {{
                themeIcon.textContent = savedTheme === 'dark' ? '☀️' : '🌙';
            }}
        }})();

        function toggleStatus(questionNumber) {{
            const content = document.getElementById('status-' + questionNumber);
            const arrow = document.getElementById('arrow-' + questionNumber);
            const button = content.previousElementSibling;

            const isOpen = content.classList.contains('open');

            if (isOpen) {{
                content.classList.remove('open');
                arrow.classList.remove('open');
                button.setAttribute('aria-expanded', 'false');
                content.setAttribute('aria-hidden', 'true');
            }} else {{
                content.classList.add('open');
                arrow.classList.add('open');
                button.setAttribute('aria-expanded', 'true');
                content.setAttribute('aria-hidden', 'false');
            }}
        }}

        // Keyboard navigation support
        document.addEventListener('keydown', function(event) {{
            if (event.target.classList.contains('status-toggle')) {{
                if (event.key === 'Enter' || event.key === ' ') {{
                    event.preventDefault();
                    event.target.click();
                }}
            }}
        }});

        // Search functionality
        let searchTimeout;
        const searchInput = document.getElementById('searchInput');
        const clearButton = document.getElementById('clearSearch');
        const searchResultsInfo = document.getElementById('searchResultsInfo');
        const questionsGrid = document.getElementById('questionsGrid');
        const noResultsDiv = document.getElementById('noResults');

        function performSearch() {{
            const searchTerm = searchInput.value.toLowerCase().trim();
            const questionCards = questionsGrid.querySelectorAll('.question-card');
            let visibleCount = 0;
            let totalCount = questionCards.length;

            questionCards.forEach(card => {{
                const questionNumber = card.querySelector('.question-number').textContent.toLowerCase();
                const questionText = card.querySelector('.question-text').textContent.toLowerCase();
                
                const matches = questionNumber.includes(searchTerm) || questionText.includes(searchTerm);
                
                if (matches) {{
                    card.classList.remove('hidden');
                    visibleCount++;
                }} else {{
                    card.classList.add('hidden');
                }}
            }});

            // Update UI based on results
            if (searchTerm === '') {{
                searchResultsInfo.textContent = '';
                clearButton.classList.remove('visible');
                noResultsDiv.style.display = 'none';
                questionsGrid.style.display = 'grid';
            }} else {{
                clearButton.classList.add('visible');
                if (visibleCount === 0) {{
                    searchResultsInfo.textContent = '';
                    noResultsDiv.style.display = 'block';
                    questionsGrid.style.display = 'none';
                }} else {{
                    searchResultsInfo.textContent = `Showing ${{visibleCount}} of ${{totalCount}} questions`;
                    noResultsDiv.style.display = 'none';
                    questionsGrid.style.display = 'grid';
                }}
            }}
        }}

        function clearSearch() {{
            searchInput.value = '';
            performSearch();
            searchInput.focus();
        }}

        // Debounced search as user types
        searchInput.addEventListener('input', function() {{
            clearTimeout(searchTimeout);
            searchTimeout = setTimeout(performSearch, 300);
        }});

        // Also search on Enter key
        searchInput.addEventListener('keypress', function(event) {{
            if (event.key === 'Enter') {{
                clearTimeout(searchTimeout);
                performSearch();
            }}
        }});

        // Splash screen initialization
        window.addEventListener('load', function() {{
            // Wait for boot sequence to complete (3 seconds)
            setTimeout(function() {{
                const splashScreen = document.getElementById('splash-screen');
                splashScreen.classList.add('hidden');

                // Remove the splash screen from DOM after animation completes
                setTimeout(function() {{
                    splashScreen.remove();
                }}, 600); // Match the fade-out animation duration
            }}, 3000);
        }});
    </script>
</body>
</html>
""")

    return "".join(html_parts)


def main():
    """Main function to orchestrate HTML generation."""
    print("🚀 Starting index.html generation...")
    print("")

    # Step 1: Parse questions
    print("Step 1: Parsing questions from questions.md")
    questions = parse_questions("questions.md")
    if not questions:
        print("⚠️  Warning: No questions found. Cannot generate HTML.")
        return 1
    print("")

    # Step 2: Parse status badges
    print("Step 2: Parsing status badges from status.md")
    status_badges = parse_status_badges("status.md")
    print("")

    # Step 3: Generate HTML
    print("Step 3: Generating index.html")
    html_content = generate_html(questions, status_badges)
    print(f"✅ Generated HTML with {len(questions)} question cards")
    print("")

    # Step 4: Write to file
    print("Step 4: Writing to index.html")
    try:
        with open("index.html", "w", encoding="utf-8") as f:
            f.write(html_content)
        print("✅ index.html successfully generated!")
    except Exception as e:
        print(f"❌ Error writing index.html: {e}")
        return 1

    print("")
    print("🎉 Done! index.html has been created.")
    print(f"📊 Generated page with {len(questions)} questions")
    return 0


if __name__ == "__main__":
    exit(main())
